### ISSUE TITLE
Adding labels to registry issue list

### ISSUE THREAD

**Issue by pdehaye** [datasets/registry#126]
I would like to start assigning GitHub labels to the GitHub issues for the registry, but need to be "contributor" for that. 
(I also want to change the label colors so they match the diagram here: http://data.okfn.org/doc/core-data-curators )

**Comment by rgrp** [comment]
@pdehaye you should now have invitation to join the org with the relevant permissions.

**Comment by pdehaye** [comment]
Started now.

**Comment by rgrp** [comment]
@pdehaye just want to say you are doing a great job here - as well as with the comments!

**Comment by pdehaye** [comment]
Thanks for the encouragements. Will try to organise things a bit. In particular I would like to have an easy funnel for newcomers to get started.
