### ISSUE TITLE
not working email

### ISSUE THREAD

**Issue by yetzt** [datasets/registry#140]
the email address `datasets@okfn.org`, stated as a contact for this organisation, does not work.

**Comment by rgrp** [comment]
@yetzt that's right - its a stub email for github to use. If you want to contact us post here: https://discuss.okfn.org/c/open-knowledge-labs/core-datasets

And yes, i guess we could set up an auto-responder telling you that ;-)

**Comment by yetzt** [comment]
you could also decide to not display a public email adress

**Comment by rgrp** [comment]
@yetzt good suggestions and fixed :-) (I think we had it public initially because it gives you the gravatar).
