### ISSUE TITLE
Global Sea level rise 

### ISSUE THREAD

**Issue by Snekili** [datasets/registry#141]
[Global Average Absolute Sea Level Change, 1880-2014][data] from the US Environmental Protection Agency using data from CSIRO, 2015;  NOAA, 2015.

[data]: http://www3.epa.gov/climatechange/science/indicators/oceans/sea-level.html

This data contains "cumulative changes in sea level for the world’s oceans since 1880, based on a combination of long-term tide gauge measurements and recent satellite measurements. [It] shows average absolute sea level change, which refers to the height of the ocean surface, regardless of whether nearby land is rising or falling. Satellite data are based solely on measured sea level, while the long-term tide gauge data include a small correction factor because the size and shape of the oceans are changing slowly over time. (On average, the ocean floor has been gradually sinking since the last Ice Age peak, 20,000 years ago.)"

## Data

Data in CSV can be downloaded here http://www3.epa.gov/climatechange/images/indicator_downloads/sea-level_fig-1.csv

Sources:

* CSIRO (Commonwealth Scientific and Industrial Research Organisation). 2015 update to data originally published in: Church, J.A., and N.J. White. 2011. Sea-level rise from the late 19th to the early 21st century. Surv. Geophys. 32:585–602. www.cmar.csiro.au/sealevel/sl_data_cmar.html.

* NOAA (National Oceanic and Atmospheric Administration). 2015. Laboratory for Satellite Altimetry: Sea level rise. Accessed June 2015. www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/LSA_SLR_timeseries_global.php.

* NOAA (National Oceanic and Atmospheric Administration). 2015 update to data originally published in: NOAA. 2009. Sea level variations of the United States 1854–2006. NOAA Technical Report NOS CO-OPS 053. www.tidesandcurrents.noaa.gov/publications/Tech_rpt_53.pdf.

## Data from CSIRO 

Data in CSV can be downloaded here
http://www.cmar.csiro.au/sealevel/GMSL_SG_2011_up.html

2015 update to data originally published in: Church, J.A., and N.J. White. 2011. Sea-level rise from the late 19th to the early 21st century.

There are four types of time series data 

  * Monthly data from 1993-2013 - CSIRO_ALT_gmsl_mo_2015

Time,“GMSL (mm)” 

1993.0417, -1.6 
1993.1250, -3.4 
1993.2083, 5.5
1993.2917, 0.1 
1993.3750, 5.3 
1993.4583, 0.2 
1993.5417, 3.9 
1993.6250, 0.2

  * Yearly data from 1993-2013 - CSIRO_ALT_gmsl_yr_2015

Time,“GMSL (mm)” 

1993.5, 1.4 
1994.5, 2.7 
1995.5, 5.7 
1996.5, 11.4
1997.5, 16.1 
1998.5, 21.9 
1999.5, 22.1

  * Monthly data from 1880-2013 - CSIRO_Recons_gmsl_mo_2015

Time,“GMSL (mm)”,“GMSL uncertainty (mm)” 
1880.0417, -183.0, 24.2
1880.1250, -171.1, 24.2 
1880.2083, -164.3, 24.2 
1880.2917, -158.2, 24.2
1880.3750, -158.7, 24.2 
1880.4583, -159.6, 24.2 
1880.5417, -159.6, 24.2
1880.6250, -161.8, 24.2 
1880.7083, -158.9, 24.2

  * Yearly data from 1880-2013 - CSIRO_Recons_gmsl_yr_2015

Time,“GMSL (mm)”,“GMSL uncertainty (mm)” 
1880.5, -158.7, 24.2 
1881.5,-153.1, 24.2 
1882.5, -169.9, 23.0 
1883.5, -164.6, 22.8 
1884.5, -143.7,22.2 
1885.5, -145.2, 21.9 
1886.5, -147.6, 20.8 
1887.5, -153.2, 20.8
1888.5, -151.1, 20.8

The paper describing this is: Church, J. A. and N.J. White (2011), Sea-level rise from the late 19th to the early 21st Century. Surveys in Geophysics, doi:10.1007/s10712-011-9119-1. This paper is published "Open Access" and is available as a pdf from here http://link.springer.com/article/10.1007%2Fs10712-011-9119-1

**Abstract** - Key Findings 

We estimate the rise in global average sea level from satellite altimeter data for 1993–2009 and from coastal and island sea-level measurements from 1880 to 2009. **For 1993–2009** and after correcting for glacial isostatic adjustment, **the estimated rate of rise is 3.2 ± 0.4 mm year−1 from the satellite data and 2.8 ± 0.8 mm year−1 from the in situ data.** **The global average sea-level rise from 1880 to 2009 is about 210 mm.** The linear trend from 1900 to 2009 is 1.7 ± 0.2 mm year−1 and since 1961 is 1.9 ± 0.4 mm year−1. There is considerable variability in the rate of rise during the twentieth century but there has been a statistically significant acceleration since 1880 and 1900 of 0.009 ± 0.003 mm year−2 and 0.009 ± 0.004 mm year−2, respectively. **Since the start of the altimeter record in 1993, global average sea level rose at a rate near the upper end of the sea level projections of the Intergovernmental Panel on Climate Change’s Third and Fourth Assessment Reports.** However, the reconstruction indicates there was little net change in sea level from 1990 to 1993, most likely as a result of the volcanic eruption of Mount Pinatubo in 1991.

## License  

Figures marked "CSIRO", are copyright CSIRO, but please feel free to use them, conditional on the figures not being altered, and their source being acknowledged, and with a link to this site where possible.
All other figures are copyright. Please do not copy without the owner's permission.

# Data from NOAA

NOAA/NESDIS/STAR 

Data is covering Global mean sea level measurements from 1992-2015
The following tables provide estimates of sea level rise based on measurements from satellite radar altimeters. Plots and time series are available for TOPEX/Poseidon (T/P), Jason-1, and Jason-2, which have monitored the same ground track since 1992, and for most of the altimeters that have operated since 1991, including T/P, Jason-1, Jason-2, ERS-2, GFO, and Envisat.

There are four types of data:

TOPEX, Jason-1, and Jason-2

  *  Seasonal signals retained 
http://www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/slr/slr_sla_gbl_keep_txj1j2_90.csv

year,TOPEX/Poseidon,Jason-1,Jason-2 

1992.9614,-17.47000,,
1992.9865,-17.67000,, 
1993.0123,-14.67000,, 
1993.0407,-20.27000,,

  *  Seasonal signals removed
http://www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/slr/slr_sla_gbl_free_txj1j2_90.csv

year,TOPEX/Poseidon,Jason-1,Jason-2 

1992.9614,-21.13000,,
1992.9865,-20.13000,, 
1993.0123,-15.92000,, 
1993.0407,-20.29000,,
1993.0660,-23.23000,, 
1993.0974,-25.36000,,

Multiple altimeters

  *  Seasonal signals retained 
http://www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/slr/slr_sla_gbl_keep_all_66.csv

year,TOPEX/Poseidon,ERS-2,GFO,Jason-1,Envisat,Jason-2,SARAL

1992.9614,-17.37000,,,,,, 
1992.9865,-17.57000,,,,,,
1993.0123,-14.57000,,,,,, 
1993.0407,-20.17000,,,,,,
1993.0660,-24.07000,,,,,, 
1993.0974,-27.17000,,,,,,
1993.1206,-24.77000,,,,,,

  *  Seasonal signals removed
http://www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/slr/slr_sla_gbl_free_all_66.csv

year,TOPEX/Poseidon,ERS-2,GFO,Jason-1,Envisat,Jason-2,SARAL

1992.9614,-21.02000,,,,,, 
1992.9865,-20.03000,,,,,,
1993.0123,-15.82000,,,,,, 
1993.0407,-20.18000,,,,,,
1993.0660,-23.12000,,,,,, 
1993.0974,-25.25000,,,,,,
1993.1206,-22.31000,,,,,, 
1993.1493,-18.23000,,,,,,
1993.1765,-17.45000,,,,,,

*Disclaimer for Experimental Satellite Data Products fom* [NOAA STAR Center for Satellite Applications and Research](http://www.star.nesdis.noaa.gov/star/productdisclaimer.php)

# License

Users are free to use the images or information hosted on this site as they wish, as long as credit is given to the NOAA / NESDIS Center for Satellite Applications and Research.

**Comment by Snekili** [comment]
Data at > http://www.cmar.csiro.au/sealevel/sl_hist_last_decades.html

**Comment by rgrp** [comment]
@Snekili could you link the actual data e.g. the CSV or Excel file on the source website.

Also I generally recommend putting the info in the main description of the issue rather than in a comment ;-)

**Comment by Snekili** [comment]
@rgrp And this one?

**Comment by rgrp** [comment]
@Snekili good. Some quick feedback:

* The description describes the graph not the dataset. I really want a description I could copy and paste into the README for this dataset (as discussed). You can find lots of examples of these introductory paragraphs - plus the more detailed description in the datasets found here https://github.com/datasets
* Formatting matters so e.g. it would be nice to not have a " " before ":" and it would look better all on one line and to be more descriptive in the title e.g.   
    The recommended dataset is [Sea Level data from the US EPA Climate Change Indicators](http://www3.epa.gov/climatechange/science/indicators/oceans/sea-level.html)
* No need to do @rgrp in the main description and in the comment. Leave it out of the main description.
* Please link the actual dataset if available and not just the main page e.g. here there is a link to the CSV on the page http://www3.epa.gov/climatechange/images/indicator_downloads/sea-level_fig-1.csv
  * You can get bonus points for putting a link to a preview via datapipes - you can use the wizard at http://datapipes.okfnlabs.org/wizard/ and the result here would be http://datapipes.okfnlabs.org/csv%C2%A0-d%C2%A0,/head%C2%A015/html/?url=http://www3.epa.gov/climatechange/images/indicator_downloads/sea-level_fig-1.csv
* Typos e.g. "Sugested" rather than "Suggested" - i hope your browser highlights potential typos as you type (Firefox and Chrome do)
* I'm not clear how e.g. "NOAA Glacier Mass Balance and Regime Measurements and Analysis" are relevant here - if you do list these and the title does not make relation to sea level clear may be worth a quick comment

I suggest just editing the description and correcting this.

**Comment by Snekili** [comment]
@rgrp made some changes

**Comment by rgrp** [comment]
@Snekili please identify the actual source CSV from the sources referenced. e.g. http://www.star.nesdis.noaa.gov/sod/lsa/SeaLevelRise/LSA_SLR_timeseries_global.php and http://www.cmar.csiro.au/sealevel/sl_data_cmar.html

**Comment by Snekili** [comment]
@rgrp Please take a look.

**Comment by rgrp** [comment]
@Snekili this looks good. Based on what you report i think we want the CSIRO data and the long time series from 1880 probably in both monthly and annual versions with the data package. At this point we can hand over to packagers :-)

**Comment by rgrp** [comment]
@kiliakis i think this now good to package :-)

**Comment by kiliakis** [comment]
@rgrp @Snekili I will post the package when ready ;)

**Comment by kiliakis** [comment]
@rgrp, @pdehaye  Datapackage is ready, please review. Links:
* [View] (http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Fsea-level-rise)
* [Validation] (http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.github.com%2Fkiliakis%2Fsea-level-rise%2Fmaster%2Fdatapackage.json)
* [Github] (https://github.com/kiliakis/sea-level-rise)

**Comment by pdehaye** [comment]
@kiliakis Looks good to me, please transfer ownership to datasets/ organisation. Won't fork otherwise we are back with the same horror show of the genome-sequencing-costs datapackage

**Comment by kiliakis** [comment]
Don't worry, ownership is already transferred!

**Comment by kiliakis** [comment]
Should I also make the changes in csv, txt files?

**Comment by pdehaye** [comment]
Changing ownership of repo apparently creates automatic redirects which were not fully reflected in the View/Validation link above. So it was all good, but that's one more subtlety to take into account. 

In any case, I added myself to the csv and txt files. 

So this is finished and I am closing. Thanks!

**Comment by rufuspollock** [comment]
FIXED. this is here https://github.com/datasets/sea-level-rise and https://datahub.io/core/sea-level-rise
