### ISSUE TITLE
International Chamber of Commerce Incoterms

### ISSUE THREAD

**Issue by cmsdroff** [datasets/registry#152]
International Commercial Terms (‘Incoterms’) are internationally recognised standard trade terms used in sales contracts. They’re used to make sure buyer and seller know:

* who is responsible for the cost of transporting the goods, including insurance, taxes and duties
* where the goods should be picked up from and transported to 
* who is responsible for the goods at each step during transportation

**Comment by cmsdroff** [comment]
Work has been done if this package is of interest?

Validate Link: http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fwarrantgroup%2FICC-Incoterms%2Fmaster%2Fdatapackage.json

Data Link: http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fwarrantgroup%2FICC-Incoterms

**Comment by pdehaye** [comment]
Added to the registry. Thanks for the work!
