### ISSUE TITLE
Glacier Mass Balance

### ISSUE THREAD

**Issue by Snekili** [datasets/registry#154]
Average cumulative mass balance of "reference" Glaciers worldwide from 1945-2014 sourced from [US EPA][datahome] and the [World Glacier Monitoring Service (WGMS)][wgms].
This is cumulative change in mass balance of a set of "reference" glaciers worldwide beginning in 1945. The values represents the average of all the glaciers that were measured. Negative values indicate a net loss of ice and snow compared with the base year of 1945. For consistency, measurements are in meters of water equivalent, which represent changes in the average thickness of a glacier.

[datahome]: http://www3.epa.gov/climatechange/science/indicators/snow-ice/glaciers.html
[wgms]: http://wgms.ch/data_databaseversions/

## Data

Main source is graph here http://www3.epa.gov/climatechange/science/indicators/snow-ice/glaciers.html and associated CSV data herehttp://www3.epa.gov/climatechange/images/indicator_downloads/glaciers_fig-1.csv.

According to the footnote for the graph the original source is:

> WGMS (World Glacier Monitoring Service). 2015 update to data originally published in: WGMS. 2013. Glacier mass balance bulletin no. 12 (2010–2011). Zemp, M., S.U. Nussbaumer, K. Naegeli, I. Gärtner-Roer, F. Paul, M. Hoelzle, and W. Haeberli (eds.). ICSU (WDS)/IUGG (IACS)/UNEP/UNESCO/WMO. Zurich, Switzerland: World Glacier Monitoring Service. http://wgms.ch/downloads/wgms_2013_gmbb12.pdf.
 
### Related publications:

WGMS (2015): Global Glacier Change Bulletin No. 1 (2012-2013). Zemp, M., Gärtner-Roer, I., Nussbaumer, S.U., Hüsler, F., Machguth, H., Mölg, N., Paul, F., and Hoelzle, M. (eds.), ICSU(WDS)/IUGG(IACS)/UNEP/UNESCO/WMO, World Glacier Monitoring Service, Zurich, Switzerland, 230 pp. Based on database version: doi: 10.5904/wgms-fog-2015-11.
WGMS (2013): Glacier Mass Balance Bulletin No. 12 (2010-2011). Zemp, M., Nussbaumer, S.U., Naegeli, K., Gärtner-Roer, I., Paul, F., Hoelzle, M. and Haeberli, W. (eds.), ICSU (WDS) / IUGG (IACS) / UNEP / UNESCO / WMO, World Glacier Monitoring Service, Zurich, Switzerland: 106 pp., publication based on database version:doi:10.5904/wgms-fog-2013-11.

WGMS (2012): Fluctuations of Glaciers 2005-2010 (Vol. X): Zemp, M., Frey, H., Gärtner-Roer, I., Nussbaumer, S.U., Hoelzle, M., Paul, F. & W. Haeberli (eds.), ICSU (WDS)/ IUGG (IACS)/ UNEP/ UNESCO/ WMO, World Glacier Monitoring Service, Zurich, Switzerland. Based on database version doi: 10.5904/wgms-fog-2012-11.

WGMS (World Glacier Monitoring Service). 2015 update to data originally published in: WGMS. 2013. Glacier mass balance bulletin no. 12 (2010–2011). Zemp, M., S.U. Nussbaumer, K. Naegeli, I. Gärtner-Roer, F. Paul, M. Hoelzle, and W. Haeberli (eds.). ICSU (WDS)/IUGG (IACS)/UNEP/UNESCO/WMO. Zurich, Switzerland: World Glacier Monitoring Service. http://wgms.ch/downloads/wgms_2013_gmbb12.pdf. WGMS World Glacier Monitoring Service, Zurich, Switzerland

## License

EPA is Federal Government so public domain we would assume.

WGMS make their data available as "Open access for scientific and educational purposes under requirement of correct citation":

> WGMS (2015): Fluctuations of Glaciers Database. World Glacier Monitoring Service, Zurich, Switzerland. DOI:10.5904/wgms-fog-2015-11.

## Other potential data sources 

There does seem to be more recent data because there are graphs with more recent e.g. [graphs like this on Climate.gov](https://www.climate.gov/news-features/understanding-climate/2012-state-climate-glaciers), or [PDF data like this from World Glacier monitoring service](http://wgms.ch/products_fog/) and this [PDF from WGMS](http://wgms.ch/downloads/wgms_2012_fogX.pdf). 

* Data from World Glacier Monitoring Service (WGMS): http://wgms.ch/data_databaseversions/
Here is zip file with datasets: http://wgms.ch/downloads/DOI-WGMS-FoG-2015-11.zip
Internationally collected, standardized dataset on changes in glaciers (length, area, volume, mass), based on in-situ and remotely sensed observations, as well as on reconstructions.
* [GLIMS Glacier database](http://www.glims.org). From the site: "GLIMS (Global Land Ice Measurements from Space) is a project designed to monitor the world's glaciers primarily using data from optical satellite instruments, such as ASTER (Advanced Spaceborne Thermal Emission and reflection Radiometer)." Data can be found at http://glims.colorado.edu/glacierdata/ which links to http://www.glims.org/download/. Data is large tgz files - probably containing geodata on individual glacier outlines. Stats on data contents at http://glims.colorado.edu/glacierdata/db_summary_stats.php - these show coverage from 1870 to 2011 and thousands of glaciers worldwide.
  * Relationship to WGMS World Glacier Inventory: "The GLIMS database is designed to be a logical extension of the World Glacier Inventory (WGI) of the World Glacier Monitoring Service (WGMS) and stores the full complement of the WGMS-defined glacier characteristics." [source](https://nsidc.org/glims/)
* The US EPA also have this [Graph: Average cumulative mass balance of "reference" Glaciers worldwide from 1945-2014](http://www3.epa.gov/climatechange/science/indicators/snow-ice/glaciers.html). You can get the CSV Data for the graph here: http://www3.epa.gov/climatechange/images/indicator_downloads/glaciers_fig-1.csv. According to the footnote for the graph the original source is:

   > WGMS (World Glacier Monitoring Service). 2015 update to data originally published in: WGMS. 2013. Glacier mass balance bulletin no. 12 (2010–2011). Zemp, M., S.U. Nussbaumer, K. Naegeli, I. Gärtner-Roer, F. Paul, M. Hoelzle, and W. Haeberli (eds.). ICSU (WDS)/IUGG (IACS)/UNEP/UNESCO/WMO. Zurich, Switzerland: World Glacier Monitoring Service. http://wgms.ch/downloads/wgms_2013_gmbb12.pdf.
* **NOAA** Glacier Mass Balance and Regime Measurements and Analysis, 1945-2003, Version 1
[Data can be found here](http://nsidc.org/data/g10002) but I'm not sure if this link will lead you directly, it requires registration, but here is the link for datasets: ftp://sidads.colorado.edu/pub/DATASETS/NOAA/G10002/Supplement2005/

**Comment by rgrp** [comment]
@Snekili could you link to the "homepage" for the main dataset - i.e. where do i get further info. Normally I recommend linking this in the main intro paragraph as a hyperlink in a nice way e.g. your main paragraph would have been:

```
[Measurements of Glacier Change][link] from Mark Dyurgerov of INSTAAR at the
US National Ice & Snow Data Center.

[link]: link goes here
```

**Comment by Snekili** [comment]
@rgrp I've made changes, please take a look.

**Comment by rgrp** [comment]
@Snekili looks better. BTW is it possible to find any more up to date data? This only runs to 2003 ...

**Comment by Snekili** [comment]
@rgrp 
Well compiled global data like this no... 
But there is plenty of graphs like this on [Climate.gov](https://www.climate.gov/news-features/understanding-climate/2012-state-climate-glaciers), or PDF data like this from [World Glacier monitoring service](http://wgms.ch/products_fog/) and this [PDF from WGMS](http://wgms.ch/downloads/wgms_2012_fogX.pdf) has quite nice data but its PDF. 
Then you have something like this from [AntarticGlaciers.org](http://www.antarcticglaciers.org/glaciers-and-climate/glacier-recession/) and it's pointing to various other sources of data and types of measurements, satelites etc like this [LANDSAT](http://landsat.usgs.gov/index.php), but I dont know if that is what you want. 

Maybe you can take a look at this [GLIMS Glacier database](http://glims.colorado.edu/glacierdata/)
https://nsidc.org/glims/
[Data](http://www.glims.org/download/) is in tgz. so I can't see what's in it.

**Comment by rgrp** [comment]
@Snekili please add info on WGMS and move this info from comment to other info section in main description.

**Comment by Snekili** [comment]
@rgrp WGMS info added in main description.

**Comment by rgrp** [comment]
@Snekili i'd suggested adding that info in the comment https://github.com/datasets/registry/issues/154#issuecomment-168650420 ;-)

At the moment the way it is inserted into the main description does not really make sense since you have EPA first. If WGMS is the real source let's have that as primary and list the graph, if we list at all, somewhere later. Let's talk about this quickly before you do more.

**Comment by Snekili** [comment]
@rgrp You are totally right. Made some changes :). We will talk.

**Comment by rgrp** [comment]
@kiliakis ready to package now - a very straightforward one as we will just go for reusing EPA CSV. Most of the README is done in the description above - may need some tweaking in license and suggest keeping the other info stuff in the README as useful info (BTW: i hope you can edit the description and thereby get the raw markdown - if not let me know and I will sort that!).

**Comment by kiliakis** [comment]
The package looks ready. I couldn't validate the datapackage.json due to internal server error message printed by the validator (most likely this is not my fault). Here are the rest links:
* [view link](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Fglacier-mass-balance)
* [actual data](https://github.com/kiliakis/glacier-mass-balance)

**Comment by rgrp** [comment]
Great. Validator is working again http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Fglacier-mass-balance

@kiliakis + @pdehaye shall we get this moved over to datasets and added to core.

**Comment by kiliakis** [comment]
@rgrp I just transferred the dataset and submitted a pull request with an updated core-list.txt . I did the same for #139 and #29 . Although I can merge in the pull request, I leave it for a managing curator.

**Comment by pdehaye** [comment]
done, thanks!
