### ISSUE TITLE
ICC-Incoterms

### ISSUE THREAD

**Issue by cmsdroff** [datasets/registry#155]
@pdehaye the ICC-Incoterms dataset has been forked over instead of transferred to datasets.

Ive added you as admin so you can make the transfer, let me know if you need anything more on this one from me?  Think you just need to delete the fork and then transfer the ownership.  Thanks for help on other sets last night.

**Comment by pdehaye** [comment]
Thanks for flagging that. Now done. FYI: I think you had enough admin rights to do the transfer yourself, although it would have been slightly complicated by the repo already existing. 

Next time you try it directly   :)
