### ISSUE TITLE
Csv vs txt in the registry. txt needs to be deprecated

### ISSUE THREAD

**Issue by pdehaye** [datasets/registry#159]
Question to @rgrp: when including a new dataset in core, I need to add it to core-list.txt, and apparently do something else. You mention a few times in the issues that it needs to be added to data.okfn.org too. I couldn't find where? Is this not automated? If not, I will go back and make sure both files are in sync.

**Comment by pdehaye** [comment]
Flaggin in @femtotrader as they might have some part of the answer: I see you changed the registry a while ago, and turned it into a datapackage. 
However it is not clear to me how the `core-list.txt` and the `core-list.csv` are meant to be kept in sync, or how it interacts with the automated scraping. I have been managing curator for a few weeks and have exclusively updated `core-list.txt` whenever I added a new dataset. This might need some fixing. Can you explain things informally here and then I ll repair my mistakes? Thanks

**Comment by rgrp** [comment]
@pdehaye great question. We basically need to deprecate the txt and move to the csv. We need to check the code in data.okfn.org is updated for this e.g. https://github.com/okfn/data.okfn.org/blob/master/lib/config.js and consuming code in lib/model.js.

In terms of it going live. Once core-list is updated we just need to visit `http://data.okfn.org/admin/reload` to get site to reindex the package list.

**Comment by cmsdroff** [comment]
Just a thought on this, could a phing script watch out for change on GitHub and run the refresh automatically?  We use team city to monitor our hit hub repos and 'on change' they run an update script.  Just a suggestion?

Sent from my iPhone

> On 26 Jan 2016, at 13:30, Rufus Pollock <notifications@github.com> wrote:
> 
> @pdehaye great question. We basically need to deprecate the txt and move to the csv. We need to check the code in data.okfn.org is updated for this e.g. https://github.com/okfn/data.okfn.org/blob/master/lib/config.js and consuming code in lib/model.js.
> 
> In terms of it going live. Once core-list is updated we just need to visit http://data.okfn.org/admin/reload to get site to reindex the package list.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



All business is conducted subject to Warrant Group Limited Standard Terms and Conditions 2012, a copy of which is available on request and at www.warrant-group.com/terms.  
Registered Office: Warrant House, 157 Regent Road, Liverpool, L5 9TF. Registered in England No. 1941659 VAT Reg. No. GB 100116496.

**Comment by tfmorris** [comment]
WTF? OpenData is subject to some secret set of conditions from a "warrant house"?

**Comment by cmsdroff** [comment]
Clearly an email footer Tom added from server?!


Sent from my iPhone

> On 26 Jan 2016, at 16:40, Tom Morris <notifications@github.com> wrote:
> 
> WTF? OpenData is subject to some secret set of conditions from a "warrant house"?
> 
> —
> Reply to this email directly or view it on GitHub.
> 



All business is conducted subject to Warrant Group Limited Standard Terms and Conditions 2012, a copy of which is available on request and at www.warrant-group.com/terms.  
Registered Office: Warrant House, 157 Regent Road, Liverpool, L5 9TF. Registered in England No. 1941659 VAT Reg. No. GB 100116496.

**Comment by rgrp** [comment]
@tfmorris sorry i don't get the context for your comment in this thread? Where's the reference for the "warrant house" that you mention?

**Comment by cmsdroff** [comment]
@rgrp @tfmorris no need to follow up, I replied by email and our server adds a footer with company terms etc, logged in and cleaned up thread when I had access from desktop to avoid further upset

**Comment by femtotrader** [comment]
see https://github.com/datasets/registry/issues/112
and https://github.com/datasets/registry/pull/115

my opinion is that data.okfn.org site should use a JavaScript DataPackage client
