### ISSUE TITLE
GINI index

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#179]
GINI is inequality index. Want this for as many countries as possible for as long as possible.

**Comment by zelima** [comment]
we could use  world bank data: http://data.worldbank.org/indicator/SI.POV.GINI

**Comment by rgrp** [comment]
@zelima great.

@gsilvapt i suggest you take this on and @zelima can advise as necessary.

**Comment by gsilvapt** [comment]
As soon as we take care of packaging those two others, this is my next one then :+1:

**Comment by gsilvapt** [comment]
There you go: https://github.com/gsilvapt/gini-index/issues/1

That one is working, apparently. What are the next steps?

**Comment by rgrp** [comment]
@gsilvapt please do post the validation and view links here ;-)

Also have you scripted the extraction so this can be run again and again automatically - you may want to look at #165 for an example of doing this with other World Bank data.

**Comment by gsilvapt** [comment]
**Validator:** http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Viewer:** http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

No, I haven't created a Python script. Still struggling with the other data package. I can work out on something yes, makes sense :smile:

**Comment by rgrp** [comment]
@gsilvapt we really need it scripted to go in so that it is repeatable. You may want to look at other scripted world banks ones e.g. #165 

Again we will also want the data "normalized" here so:

```
Year, Country Code, Country, Value
```

**Comment by gsilvapt** [comment]
Should that be the format of all data packages? I don't recall reading about that in the guides. Perhaps it should be added, if not already? Sorry for the off-topic question.

And yes, I haven't yet worked on the python script because I thought it would be better to prepare the datapackage and then work on that. Specially when other issues require the same script. Thanks for the guidance! ;)

**Comment by gsilvapt** [comment]
[Latest commit](https://github.com/gsilvapt/gini-index/commit/60ad090ea7558b059c6d559e2c9f4897b0d36bd9) takes care of "normalizing" data.

**Validator:** http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index%2F

**Viewer:** http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Comment by rgrp** [comment]
@zelima can you review please and comment.

**Comment by zelima** [comment]
Data is sorted by country names alphabetically, but not sorted by year. As an example:
```
Albania,ALB,1996,27.01
Albania,ALB,2005,30.6
Albania,ALB,2002,32.46
Albania,ALB,2012,29.98
Albania,ALB,2008,28.96
```
Think it would be better if it is sorted.
```
Albania,ALB,1996,27.01
Albania,ALB,2002,30.6
Albania,ALB,2005,32.46
Albania,ALB,2008,29.98
Albania,ALB,2012,28.96
```
Also REAMDE.md doesn't need Title as an opening line.
It would be good if you add README.md for usage in scripts directory eg: [like this] (https://github.com/datasets/commodity-prices/tree/master/scripts)
We could also add Makefile eg: [like this](https://github.com/datasets/commodity-prices/blob/master/Makefile) (We need Makefile, right? @rgrp)

Overall it looks good to me. Great job @gsilvapt

**Comment by gsilvapt** [comment]
Thanks for reviewing @zelima! Yes, the year sorting was something I was worried before but I guess we can work that out before publishing it.

Anyway, the to-do list for this package is:
- [ ] sort data frame by country (alphabetically) *and* by year (ascending);
- [ ] prepare Python script to run automatically as per https://github.com/datasets/registry/issues/165

**Comment by rgrp** [comment]
@gsilvapt yes you want a makefile as per @zelima - in general you can follow @zelima's suggestions 😄

**Comment by gsilvapt** [comment]
Alright. I will have to read more about Makefiles and will have to work on something for all the other data packages then. Thanks, @zelima and @rgrp!

**Comment by gsilvapt** [comment]
Newest version:

**Validator:** http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Viewer:** http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

`Makefile` has been added and script is currently working.

Can anyone check if everything is correct this time? @rgrp @zelima Thanks!!

**Comment by zelima** [comment]
Just a little correction - Think it will be better if country names are sorted in ascending order as well (From "A" to "Z").
After this fix Datapackage looks perfect to me.
well done @gsilvapt !!!

**Comment by gsilvapt** [comment]
Didn't even noticed that. Weird though. I though I had it sorting things correctly. Thanks, @zelima!

**Validator:** http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Viewer:** http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fgsilvapt%2Fgini-index

**Comment by zelima** [comment]
@gsilvapt Great! 
@rgrp To me, this one is ready to publish.

**Comment by rgrp** [comment]
@zelima great. Can you work with @gsilvapt to get it moved over and published on the site.

**Comment by gsilvapt** [comment]
@zelima @rgrp I have the PR ready to publish the updated lists upstream. I don't know how can I transfer ownership, though.

**Comment by zelima** [comment]
@rgrp I've never published anything on the site, some help would be useful.

**Comment by rgrp** [comment]
@zelima read http://data.okfn.org/doc/core-data-curators#4-publishing - then ping me on gitter if help needed.

**Comment by zelima** [comment]
@gsilvapt Go do repository settings, scroll down where the Danger zone is and click on transfer, fill the pop-up window as needed and as much as I remember that's all.

**Comment by gsilvapt** [comment]
That requires authorization: `You don’t have admin rights to datasets`

**Comment by zelima** [comment]
@gsilvapt  Make sure you are in  [**your**](https://github.com/gsilvapt/gini-index ) repository settings

**Comment by gsilvapt** [comment]
@zelima I need to become a member of the organization before changing ownership, thus it says "admin rights to datasets", where `datasets` is the organization I am trying to transfer to

**Comment by zelima** [comment]
I'm not sure I have permission to make somebody a member of organization. @rgrp Think we need your help.

**Comment by gsilvapt** [comment]
@zelima @rgrp I can take a print screen if needed

**Comment by rgrp** [comment]
@zelima i have added @gsilvapt to the curators team and made you a "team maintainer" so you can add people going forward. https://github.com/orgs/datasets/teams/curators

I will now leave you two to manage the move-over of the repository.

**Comment by gsilvapt** [comment]
@rgrp, thanks!

@zelima I am making the transfer now ;)

**Comment by zelima** [comment]
@rgrp @gsilvapt PR is read https://github.com/datasets/registry/pull/185
We need merge and after I'll publish.

**Comment by gsilvapt** [comment]
Merged!

**Comment by zelima** [comment]
The data has landed here:  http://data.okfn.org/data/core/gini-index

**Comment by gsilvapt** [comment]
Data package available online. FIXED!

**Comment by rgrp** [comment]
@pdehaye can we tweet about this one?
