### ISSUE TITLE
[meta] Set up waffle.io for this issue tracker

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#183]
Would make it a lot easier to analyse status and progress of things.

**Comment by sabas** [comment]
What about using projects?
https://help.github.com/articles/about-projects/

**Comment by rufuspollock** [comment]
@sabas good suggestion and may use that rather than waffle for the moment.

Overall, having thought further, i don't think we necessarily need either atm so i'm going to close this as WONTFIX for now.

**Comment by rufuspollock** [comment]
WONTFIX.
