### ISSUE TITLE
Messed up layout in "community" packages with gigantic sources

### ISSUE THREAD

**Issue by gsilvapt** [datasets/registry#187]
Under `Country and Regional Analyses (CRA) - UK Government Finances` and `Hotline SOS Démocratie 2013.` in the *Community Datasets list, there are two gigantic lists of sources that should be reduced for the sake of design and page layout.

**Comment by rgrp** [comment]
@gsilvapt this is not a datasets issue but a UX / design issue so could you please re-file in https://github.com/okfn/data.okfn.org-new/issues (screenshot valuable).
