### ISSUE TITLE
Missing values in data csv files

### ISSUE THREAD

**Issue by rgieseke** [datasets/registry#189]
GitHub complains about missing data to render the CSVs in `data`:

"It looks like row 71 should actually have 4 columns, instead of 3."
https://github.com/datasets/registry/blob/master/data/catalog-list.csv#L71

"It looks like row 59 should actually have 4 columns, instead of 3." 
https://github.com/datasets/registry/blob/master/data/core-list.csv#L59

I think "owner" is missing ...

**Comment by zelima** [comment]
@rgieseke Great catch, Thanks!
