### ISSUE TITLE
Add employment-us to core datasets

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#216]
Currently living at: https://github.com/datasets/employment-us

For some reason this never got added to the registry list for core.

Note also that this also exists at https://old.datahub.io/dataset/us-employment-bls/resource/c3ade464-11cb-46b4-9181-27bb9505bf3d (and we can redirect)

**Comment by Mikanebu** [comment]
@rufuspollock added into [core list](https://github.com/datasets/registry/blob/master/core-list.csv) and fixed some properties https://github.com/datasets/employment-us/commit/5b014c7c2288cb6d3c0dd51ae47b6ec2ff2c72c3 according to the spec v1. And published under the `core` https://datahub.io/core/us-employment-bls .

**Comment by zelima** [comment]
@Mikanebu I believe this is now fixed. Could you please close?

**Comment by Mikanebu** [comment]
FIXED, it is live now in  https://datahub.io/core/us-employment-bls under the `core`

**Comment by rufuspollock** [comment]
@mikanebu where is the graph for this dataset (cc @zelima). Our standard practice is to add a graph and it is good practice or us to do this!

**Comment by rufuspollock** [comment]
@Mikanebu also it would have been nice to do things like add source info to the datapackage.json and maybe a note to the README. Please be **proactive** in this kind of work and go "above and beyond" in thinking what would make a high quality core dataset.

Also did you add a note about redirecting this to the redirection plan spreadsheet?

**Comment by Mikanebu** [comment]
@rufuspollock Thanks for this advise, I will update it with `sources` property and update `readme.md` as well. In the future, I will be more proactive. Added into redirection plan spreadsheet

**Comment by rufuspollock** [comment]
@Mikanebu can you also add a graph.

**Comment by rufuspollock** [comment]
@Mikanebu is this live on datahub.io yet? Can you link to it here once it is.

**Comment by Mikanebu** [comment]
@rufuspollock yes, I linked it when I closed this issue. See my comments ablove: https://datahub.io/core/us-employment-bls. Also, I will add graph as well

**Comment by Mikanebu** [comment]
@rufuspollock Updated with graph, added sources property into `datapackage.json` and updated `README.md`
