### ISSUE TITLE
Oil prices

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#23]
US EIA has a variety of prices: https://www.eia.gov/dnav/pet/pet_pri_spt_s1_d.htm (US EIA is great as high quality and public domain as fed gov)

There's various types of oil for which we could get prices:

* brent crude - https://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=RBRTE&f=D
  * XLS file: https://www.eia.gov/dnav/pet/hist_xls/RBRTEd.xls
* wti (west texas intermediate) - http://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=RWTC&f=M
  * note there are a bunch of versions - [first purchase price](http://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=F003048623&f=M) - [FOB spot price](http://www.eia.gov/dnav/pet/hist/LeafHandler.ashx?n=PET&s=RWTC&f=M)
* pump price (in various places in the world)

I propose we store:

* Brent crude
* WTI

For granularity I'd say it is worth storing all of daily, weekly, monthly and annual but prioritise daily. (note naming conventions: http://data.okfn.org/doc/publish-faq#data-package-name)

Question: Do this as one data package or one data package per oil type? (And if one data package do we store brent and WTI same file or separate files? Ans: yes, separate files).

All in one:

* Convenient to prepare as data all from same source so scraper easy to run (that said we already have natural gas prices separate ...)

Separate:

* One data package for one dataset approach.
* Data package is small and lightweight

My instinct here is in all in one, so data package will look like:

```
data/wti-day.csv
data/wti-year.csv
data/wti-month.csv
# etc
```

**Comment by rgrp** [comment]
@kiliakis could you look at this one.

**Comment by kiliakis** [comment]
@rgrp I am going to start packaging this one, I will put both brent crude and wti in the same datapackage, separate files. As for the temporal granularities, there will be one file for each of them, and the extension will follow the second option (day / week etc) as mentioned in data package naming conventions.
If we decide to alter any of the above though, I could easily change it.

**Comment by kiliakis** [comment]
Datapackage looks ready to me, please review. Links:
* [view](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fkiliakis%2Foil-prices)
* [validation](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.github.com%2Fkiliakis%2Foil-prices%2Fmaster%2Fdatapackage.json)
* [github](https://github.com/kiliakis/oil-prices)

@rgrp If I merge together brent and wti files of same granularity, it would be possible to display both brent-day and wti-day data series in the datapackage view graph. Currently it is displayed only a brent-day line graph.

**Comment by rgrp** [comment]
@kiliakis brilliant. What's your view on merging? My feeling is probably keep separate and work on changing the view stuff so that it can support multiple series.

@kiliakis + @pdehaye can we get this moved over and added to the core list.

**Comment by pdehaye** [comment]
@rgrp  will try to start doing this in 10 hours or so. have been very busy past week

**Comment by pdehaye** [comment]
@kiliakis actually, I need you to transfer ownership of the dataset. I have just reviewed and it looks good to go! you can do a pull request to add to the core list if you want, or signal for me that I need to do it.

**Comment by pdehaye** [comment]
@kiliakis would be great to get this done! just transfer ownership if you have little time.

**Comment by kiliakis** [comment]
done (sorry for the delay, I will be back soon)

**Comment by pdehaye** [comment]
Now fully packaged! Thanks, @kiliakis!

**Comment by rgrp** [comment]
When complete can you close with a comment like:

```
FIXED.

{link to data.okfn.org package}
{link to github package}
{link to tweet if we tweeted}
```

That would be awesome and mean that checking later it is really easy to see where this ended up.

**Comment by pdehaye** [comment]
ok

**Comment by rgrp** [comment]
@pdehaye great! could you do it for this one ;-)
