### ISSUE TITLE
Codes for Units of Measure Used in International Trade

### ISSUE THREAD

**Issue by sabas** [datasets/registry#231]
UNECE Recommendation 20
Transform and normalize an Excel file
https://www.unece.org/fileadmin/DAM/uncefact/recommendations/rec20/rec20_Rev13e_2017.xls

**Comment by rufuspollock** [comment]
@sabas brilliant - would you be up for packaging?

**Comment by sabas** [comment]
I made this, removing the symbols and conversion columns because they had a lot of symbols that broke in the conversion. If it's acceptable I move to the datasets org
https://github.com/sabas/unece-units-of-measure

**Comment by rufuspollock** [comment]
@sabas can you report whether you have validated this i.e. run `data validate` on the dataset using the `data` command line tool https://datahub.io/docs/features/data-cli

@Mikanebu (and @zelima) can you review @sabas new dataset here and if acceptable let's get it across.

**Comment by anuveyatsu** [comment]
@sabas Hi! It seems like you're using older NodeJS version - you need version `>7.6`.

**Comment by sabas** [comment]
Thank you @anuveyatsu I upgraded to the latest version
@rufuspollock I fixed the json accordingly and validated

**Comment by Mikanebu** [comment]
@sabas Great! There is one typo in https://github.com/sabas/unece-units-of-measure/blob/83b6ed270f8d44355b800f7a03f27937843e3e35/datapackage.json#L5 (`licenses` instead of `licensces`). Also, including `Preparation` section to `readme.md` would be bonus point. Please, see https://github.com/datasets/pharmaceutical-drug-spending

**Comment by sabas** [comment]
Done.

**Comment by Mikanebu** [comment]
@sabas Thanks! 
@zelima It is ready to go under `datasets` organization. Do I need to publish it under `core`? 
cc: @rufuspollock

**Comment by zelima** [comment]
@Mikanebu yes, let's transfer the ownership and publish under core

**Comment by Mikanebu** [comment]
@sabas Could you transfer ownership to the datasets org ? I will publish under `core`

**Comment by sabas** [comment]
https://github.com/datasets/unece-units-of-measure here it is @Mikanebu

**Comment by Mikanebu** [comment]
@sabas Well done! 🎆It is available now on https://datahub.io/core/unece-units-of-measure. Also, added into registry https://datahub.io/core/registry. Added description and link to DataHub https://github.com/datasets/unece-units-of-measure.

**Comment by rufuspollock** [comment]
@sabas awesome work - and you should become an official member of the data curator team and get a badge, see #232

**Comment by rufuspollock** [comment]
@Mikanebu do you want to close the issue with a FIXED statement?

**Comment by Mikanebu** [comment]
FIXED, the dataset is live now on DataHub https://datahub.io/core/unece-units-of-measure. Added into datasets org https://github.com/datasets/unece-units-of-measure.
