### ISSUE TITLE
CO2 emissions (by country)

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#27]
Time series of C02 emissions (globally and by country).

Time range: as long as possible and as up to date as possible
## Datasets

Think we have multiple:
- `co2-{geo}`
  - total and per capita emissions at level `{geo}` which is one of `global` or `national`
- `co2-fossil-{geo}` where geo is one of `global | national | regional`
  - global: http://cdiac.esd.ornl.gov/trends/emis/tre_glob_2010.html
  - country data is at http://cdiac.esd.ornl.gov/trends/emis/tre_coun.html
  - preliminary estimates for 2011/2012 - http://cdiac.ornl.gov/ftp/trends/co2_emis/Preliminary_CO2_emissions_2012.xlsx
- `co2-fossil-gridded` - http://cdiac.esd.ornl.gov/epubs/ndp/ndp058/ndp058_v2013.html
## Sources

http://cdiac.esd.ornl.gov/
## Data Should Look Like

Global:

```
Year, Emissions, .... could have other columns for more fine-grained breakdown
```

Country:

```
Year, Country, Emissions, Per Capita Emissions
```

**Comment by rgrp** [comment]
Only global done. Reopening for by country.

**Comment by kiliakis** [comment]
Hi @rgrp , annual co2 fossil-fuel per country data are uploaded in my git: https://github.com/kiliakis/co2-emissions .

Links I used for Data package validator and viewer:
* Validation link: https://raw.github.com/kiliakis/co2-emissions/master/datapackage.json
* View link: https://raw.github.com/kiliakis/co2-emissions/master

A snapshot from data package viewer: 
 
![screenshot from 2015-12-02 00 01 49](https://cloud.githubusercontent.com/assets/11835649/11515725/0a5ee2e8-9888-11e5-9c4a-15451a38ccca.png)

Waiting for any feedback.

**Comment by pdehaye** [comment]
Put in some pull requests.

**Comment by rgrp** [comment]
@kiliakis as a tip it is best to actually link the validation results e.g. http://data.okfn.org/tools/validate?url=...

**Comment by Snekili** [comment]
Other GHG data > http://data.un.org/Explorer.aspx?d=GHG&f=seriesID%3aCH4

https://drive.google.com/drive/folders/0B_KlKJBuuX4aNjFfVDYxY2k2dnc

**Comment by zelima** [comment]
@rgrp is this one done? if not, I can finish..

**Comment by rgrp** [comment]
@kiliakis could you transfer this is to the datasets organization and then we can take it from there.

@zelima atm @kiliakis has already done most of this so let's get his repo transferred and then we can see.

**Comment by zelima** [comment]
@rgrp got it

**Comment by zelima** [comment]
@kiliakis Any thoughts about transferring? Maybe some  help needed?

**Comment by kiliakis** [comment]
@zelima I've already transferred that :) https://github.com/datasets/co2-emissions

**Comment by zelima** [comment]
@kiliakis Oh, great! 
Then we should close this one, right @rgrp ?

**Comment by rgrp** [comment]
@zelima yes, though first this should be live on data.okfn.org and we should tweet about it /cc @pdehaye (and when tweeting we usually want a nice image ...)

When closing you want to note something like:

```
FIXED

{link to live on data.okfn.org}
{link to github repo}
```

**Comment by zelima** [comment]
@pdehaye we can use this image for tweet: 
![co2emissions](https://cloud.githubusercontent.com/assets/15143785/17321525/0af49f94-58aa-11e6-9bc3-1f326979cb5e.png)

**Comment by zelima** [comment]
Link to repo: https://github.com/datasets/co2-emissions
Link to live: http://data.okfn.org/data/core/co2-fossil-global

**Comment by rgrp** [comment]
@zelima but the two links you just provided don't match - the former is the *new* dataset and the latter data.okfn.org link is to a different data package ...

**Comment by zelima** [comment]
@rgrp you are right, I've been mistaken.
So the correct links are:
Link to repo: https://github.com/datasets/co2-emissions
Link to live: http://data.okfn.org/data/kiliakis/co2-fossil-by-nation

@pdehaye image above is useless. Sorry for that. Unfortunately we don't have graph view for this one - only grid view.

**Comment by rgrp** [comment]
@zelima what would it take to get a graph view for this new dataset?

**Comment by zelima** [comment]
@rgrp There are different emission values for multiple countries for the single year. So we need to group values by country and by year too. (probably by different emission types as well) Like in this example https://vega.github.io/vega-editor/?mode=vega&spec=stocks
As much as I know Recline library does not support this kind of transforms. So we need to use different library for showing graphs like Vega.

**Comment by rufuspollock** [comment]
@AcckiyGerman can you look into estimate for getting co2-emissions dataset completed and published as a core dataset. /cc @zelima

**Comment by zelima** [comment]
@AcckiyGerman This is now possible by setting correct configuration in `views`.  See this datapackage.json  for example https://pkgstore-testing.datahub.io/81429cbbddcfb180f54c142fac32f83b/population-growth-estimates-and-projections/27/datapackage.json

**Comment by AcckiyGerman** [comment]
@rufuspollock 
https://github.com/datasets/co2-emissions has been updated:
- latest link on a source FTP (till 2014)
- script and dp.json to pass the datahub validator
- readme extended

On a datahub: https://datahub.io/AcckiyGerman/co2-fossil-by-nation
@zelima take a glance plz and I'll push it under the core user.

#### P.S. I decided not to add views because:
- here is 220 countries in the dataset
- we already have the graph re global co2-emissions (which comes from the same source) http://datahub.io/core/co2-fossil-global

**Comment by zelima** [comment]
@AcckiyGerman I Agree re views. Looks good to go

**Comment by AcckiyGerman** [comment]
FIXED
Global co2 - http://datahub.io/core/co2-fossil-global
per Nation - https://datahub.io/core/co2-fossil-by-nation

**Comment by zelima** [comment]
@AcckiyGerman Great! let's close

**Comment by zelima** [comment]
@AcckiyGerman is core list updated BTW?

**Comment by AcckiyGerman** [comment]
@zelima of cource
> latest link on a source FTP (till 2014)

2014 is the latest data on the source site, but I asked guys from http://carbondoomsday.com and hope we'll create a daily updating co2-dataset together

**Comment by AcckiyGerman** [comment]
@zelima oh, core list, right! Thanks for remembering!!!

**Comment by AcckiyGerman** [comment]
Core-list updated!

**Comment by rufuspollock** [comment]
I'm confused: what happened to co2-emissions?

I'd like a graph if possible on co2-fossil-by-nation - maybe pick some big emitters e.g. US, China.

**Comment by AcckiyGerman** [comment]
@rufuspollock 
- https://github.com/datasets/co2-emissions  on a github
- http://datahub.io/core/co2-fossil-global  is the same dataset on a datahub

Funny that before you asked I didn't see that url names are different.
That seems the 'co2-fossil-global' name comes from the `datapackage.json`, while the original github name is co2-emissions, I'm going to rename it now, if you are not objecting.
