### ISSUE TITLE
City population timeseries

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#30]
http://data.un.org/Data.aspx?d=POP&f=tableCode:240

Download is via some javascript-y thing but some dev tools analysis reveals source as:

http://data.un.org/Handlers/DownloadHandler.ashx?DataFilter=tableCode:240&DataMartId=POP&Format=csv&c=2,3,5,7,9,11,13,15,16,17&s=_countryEnglishNameOrderBy:asc,refYear:desc,areaCode:asc

**Comment by iotakodali** [comment]
@rgrp is this dataset ready to package? is there link for the data repo

**Comment by rgrp** [comment]
@jalbertbowden did you do any work here?

@iotakodali just checking with @jalbertbowden. If he has not done anything I suggest you start a repo - we'll then move it to github.com/datasets/ when ready.

**Comment by iotakodali** [comment]
@rgrp it is a 6.5 MB csv file with some footnotes for few countries. Do you think we should split them into two files?

**Comment by sxren** [comment]
@iotakodali maybe one csv with male and female data (~28,000 rows) and one csv with "both sexes" data (~14.000 rows).

**Comment by sxren** [comment]
@iotakodali are you working on this? it would be useful for #47. thanks!

**Comment by st-martin** [comment]
@rgrp @sxren
Is this okay? https://github.com/st-martin/citypop-timeseries/tree/master

**Comment by Yannael** [comment]
@st-martin Great to catch up on this one! CVSs seem fine, however there are issues with the datapackage.json. Can you update it so the validation and view are fine, see 
* http://data.okfn.org/doc/publish-faq#validate-and-preview-your-data-package for links to the validate and view tools, 
* http://data.okfn.org/doc/data-package for the structure of the datapackage.json.

Also, could you follow the guidelines http://data.okfn.org/doc/publish-faq#readme for the README?

Thanks!

**Comment by st-martin** [comment]
@Yannael Those links were really useful. Thank you!

Packaging is mostly done ([Validation link](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fst-martin%2Fcitypop-timeseries%2Fmaster%2Fdatapackage.json)) but views are not straightforward for this dataset. Are they a requirement?

**Comment by Yannael** [comment]
@st-martin oops by view I did not mean to visualize the data with Recline (which would probably be tricky with this dataset), but how the dataset page (table and README) will be displayed on OKFN website. Simply enter the URL to your dataset at http://data.okfn.org/tools/view

Sorry for the misunderstanding

**Comment by st-martin** [comment]
Don't worry! This has been useful to learn a bit more and to burnish the data package.

Here are the links:
* To my [repository](https://github.com/st-martin/citypopulation-year).
* [Validation link](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fst-martin%2Fcitypopulation-year%2Fmaster%2Fdatapackage.json).
* [View link](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fst-martin%2Fcitypopulation-year).

What's next?

**Comment by Yannael** [comment]
@st-martin 
Ok looks good!
One last thing: you should add the 'sources' structure in your datapackage.json to specify the content of the columns

You can get it from http://data.okfn.org/tools/create by upoading your CSV there, just copy and paste then sources content in youe datapackage file after

You'll see that the view at http://data.okfn.org/tools/view will then also display the table!

Once done, you can transfer ownership of your repo to me (that is in settings on the Github repo), I'll then transfer it to the dataset repo.

**Comment by st-martin** [comment]
Done!
Please, have a look at it to ensure that everything's okay and then I'll transfer the ownership.

1. [Validation](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fst-martin%2Fcitypopulation-year)
2. [View](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fst-martin%2Fcitypopulation-year)
3. [Repository](https://github.com/st-martin/citypopulation-year)

**Comment by Yannael** [comment]
@st-martin Ok, great! 
I'll add to the dataset repo when you transfer me the ownership

**Comment by Yannael** [comment]
@st-martin Can you resend the link for the transfer, it seems to be expired? Thanks!

**Comment by st-martin** [comment]
Hi, @Yannael. I'm new to GitHub and I don't know how to resend it. I don't even knew you have received a link. Isn't it already transfered?

**Comment by Yannael** [comment]
@st-martin 
Problem solved, that was on my side. I transferred it, http://data.okfn.org/data/datasets/unsd-citypopulation-year

Thanks!

@rgrp

**Comment by rgrp** [comment]
FIXED. Closing. Well done all.

@Yannael one aside - i think we may want to name this a bit differently e.g. population-city (we generally don't put providers atm and i think the year stuff is normally not included unless we are distinguishing a time series with one granularity from another).

**Comment by lexman** [comment]
Final data is here : https://github.com/datasets/population

**Comment by rgrp** [comment]
@lexman no its at https://github.com/datasets/population-city and http://data.okfn.org/data/core/population-city

/cc @pdehaye a good example of why we should list the final published locations (and one i did :wink:)

**Comment by lexman** [comment]
+1 ! 
I've been looking for this data mentionned here...
