### ISSUE TITLE
United Nations Code for Trade and Transport Locations (UN/LOCODE)

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#31]
http://www.unece.org/cefact/locode/service/location.html

**Comment by sanh2o** [comment]
Is this still open ? I can have a go at this .

**Comment by rgrp** [comment]
@sanh2o this is indeed still open - please jump in (I believe @jalbertbowden has not had a chance to progress any further here).

**Comment by sxren** [comment]
@sanh2o Just in case you missed it, there is also a CSV download for this dataset at http://www.unece.org/cefact/codesfortrade/codes_index.html.

**Comment by sanh2o** [comment]
@sxren, Good find. I am at the halfway stage scraping this, nonetheless good exercise for myself. I will see about how to package this csv.

**Comment by jalbertbowden** [comment]
guys....no excuses for being so behind, but my sincerest apologies....@sanh2o, are you good or do you want me to clean up my mess?

**Comment by sanh2o** [comment]
I have created the data package in a folder with two csv files and one index file , for some reason i was unable to add license info in the json creator. It is good to go.

**Comment by rgrp** [comment]
@sanh2o can you link your work and also can you link the validator and "preview" outputs with your data package from http://data.okfn.org/tools/validate and http://data.okfn.org/tools/view

@jalbertbowden can you review this once @sanh2o submits the links?

**Comment by jalbertbowden** [comment]
sure thing

**Comment by rgrp** [comment]
@sanh2o can you drop us the link of the data package you have prepped?

**Comment by sanh2o** [comment]
Sorry for the delay.

https://github.com/sanh2o/UNLOCODE

The file and two index files are located here. One of the files contains description of columns which can be converted to json if needed. JSON creator not working for this csv file.

**Comment by sxren** [comment]
@rgrp how does this relate to/differ from https://github.com/datasets/un-locode ?

**Comment by jalbertbowden** [comment]
i'll take a gander here in a bit. thanks!

**Comment by rgrp** [comment]
@sxren good question. I did not realize we already that much done. @sxren can you check out this vs @sanh2o and resolve and then we can close this item out.

**Comment by sxren** [comment]
@sanh2o thank you very much for your work on this dataset. please hold off on doing any additional work. @jalbertbowden, please move on to the next item in your work queue. thank you.

**Comment by sxren** [comment]
@sanh2o ok. i looked at https://github.com/datasets/un-locode. when that repo was committed last august, a link never made it into this issue. @rgrp as a preventative measure, i suggest creating a stub repo for each new issue before anyone begins work on it. even if it's it's an empty repo. what do you think?

back to @sanh2o: you have a description of the data source from the UN in your README.md. that would be a good addition to https://github.com/datasets/un-locode.

would you be up for:

* forking https://github.com/datasets/un-locode
* adding the paragraph that begins `The "United Nations Code for Trade and Transport Locations" is ...` to the `Data` section of the README.md
* making a pull request with your addition to the README.md
 
thank you very much, and i'm very sorry for not catching this the other day.

**Comment by sanh2o** [comment]
@sxren , i will make the necessary changes

**Comment by sanh2o** [comment]
@sxren, i have made the necessary changes.

**Comment by sxren** [comment]
@sanh2o the readme was already updated. let's leave it as it is for now. closing this issue.
