### ISSUE TITLE
Country Boundaries (vector)

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#38]
This would be country polygons at crudest scale (e.g. 1:110m). Suggest packaging natural earth data (pd etc).

package name: `geo-boundaries-world-110m`

Long-term: best way would be to get primary natural earth folks to add in "packaging" - they are already on github - see https://github.com/nvkelso/natural-earth-vector. But we need an exemplar ...

What format should we use?

* geojson
* topojson - already have this here https://github.com/mbostock/topojson/tree/master/examples
* (geocsv ?)
* (sqlite)

/cc @jalbertbowden @amercader - thoughts here very welcome :-)

## Data

* [natural earth geojson from @nvkelso](https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_admin_0_countries.geojson) - [just boundaries](https://github.com/nvkelso/natural-earth-vector/blob/master/geojson/ne_110m_admin_0_boundary_lines_land.geojson)
* [topojson from @mbostock](https://github.com/mbostock/topojson/blob/master/examples/world-110m.json)
* Natural earth site: http://www.naturalearthdata.com/downloads/110m-cultural-vectors/

**Comment by rgrp** [comment]
@jalbertbowden up for completing this?

**Comment by jalbertbowden** [comment]
sure. i need to do something here.

**Comment by jalbertbowden** [comment]
how do you feel about using DIVA-GIS? 
super easy to scrape, bulk conversion to geojson/topojson?  
i tried out albania's dataset, looks clean, converted easy.  
it, and i'm assuming most of the others, have more than one administrative area boundary shapefile, one showing the foreign boundaries (what we want), and each successive dividing the country up into its states/localities, to finer detail.  
so my question is, these seem pretty useful as well....should i include them entirely?  
or should i save them for now, and just get the first set done?  
or they should be omitted outright?  
http://www.diva-gis.org/

**Comment by jalbertbowden** [comment]
does natural earth have each jurisdiction broken out into separate files?  
i've been over their downloads numerous times trying to clarify and not ask the obvious...but if they have it, i'm totally overlooking it.  
  
if they don't, thoughts on what datasets to use? i was just looking at DIVA-GIS, and i think it'll do nicely, if need be.

**Comment by nvkelso** [comment]
you'd need to use a command line tool like ogr2ogr (in the gdal family) to
filter &/or clip out the per country information from natural earth.

**Comment by jalbertbowden** [comment]
werd. i'll see what i can dig up

**Comment by jalbertbowden** [comment]
think i found it here. ogr2ogr -f "ESRI Shapefile" -where 'SOVISO="FR"' FRANCE_110m_admin_0_co  
working on this now

**Comment by ThomasG77** [comment]
Is it working on your side? I've forked the repository and automated extraction per countries and added the shp files at https://github.com/ThomasG77/geo-boundaries-world-110m
The only remaining part IMO is documenting all fields.

As I was working on the fields part, I was wondering if there is a way to declare a schema and make a reference in datapackage (a bit like in xml). I produced the per countries GeoJSON and the fields schema remains the same. So duplicating, 177 times is not really good IMO.

**Comment by jalbertbowden** [comment]
no i'm still having an issue. jvm.dll not found. thinking about wiping the desktop and starting over. 
agree about duplication....if you would like me to help with the fields, lmk

**Comment by ThomasG77** [comment]
@jalbertbowden Can you help for the fields? See https://github.com/ThomasG77/geo-boundaries-world-110m/blob/master/datapackage.json#L30
I've some missing fields undocumented (I will duplicate fields metadata for each country file after)
@nvkelso Any feedback, additions as your are the original data producer?

**Comment by nvkelso** [comment]
What do you need help with? What fields need documenting?

**Comment by ThomasG77** [comment]
The fields I mentioned are from https://github.com/ThomasG77/geo-boundaries-world-110m/blob/master/datapackage.json#L31 to https://github.com/ThomasG77/geo-boundaries-world-110m/blob/master/datapackage.json#L407
Each of them looks like below
```
 {
    "name": "woe_id",
    "title": "",
    "type": "number",
    "description": ""
},
...
```
As you see, I always have the field `name` and `type. The undocumented parts are in `title` and `description`. In some cases, I was able to guess (or I think) but I'm stuck for some of them. Any help is appreciated.

**Comment by jalbertbowden** [comment]
guys i keep getting slammed on every front. i'm sorry i'm not being much help. i do plan on helping alot, i just need to get some things in order first. until then, i'll try and comment when i can, but with my current schedule i'm not even getting on here daily like i used to.
carry on, you're doing a great job.
i'm sorry for letting you down

**Comment by rgrp** [comment]
@jalbertbowden are you able to help @ThomasG77 resolve this one issue? then we can get this up. wdyt?

**Comment by jalbertbowden** [comment]
ok. i have hobbled a gist of *some and relevant links to try and piece it together, but its really a mess. there is no clear definition.  
you'll see if you follow the links in this gist.
i commented on the issue with the gist and links too....hopefully we'll get some feedback.  
https://github.com/nvkelso/natural-earth-vector/issues/121  
here's the gist, i just did Afghanistan:  
https://gist.github.com/jalbertbowden/1a94aa339682eabfdc6a

**Comment by lexman** [comment]
Hello,

is someone still working on this ? I'm quite familiar with org so I can maintain this datapackage. 

What fields should we include ? A really minimalist set (geometric shape of the country, common name of the country, ISO3 code of the country) that is meant to be joined with the very complete https://github.com/datasets/country-codes ? Or should we include all or partial data from the former ?

By the way, should we split countries withe their overseas parts (eg France and La Réunion) or should we gather them in the same multiple geometric shape ?

**Comment by jalbertbowden** [comment]
not sure if anyone is still actively pursuing this....i know i haven't done anything since my last post. still have not heard back from natural earth.  

fields to include:
preferably all the fields that we already have....you can view them in the repository.

not sure about all/partial data from the former....

not sure about splitting countries either....hopefully others can comment.

essentially we need all of the fields we are using defined. realistically, we'll take any fields that we can get defined, and we seriously appreciate it.

thanks @lexman!

**Comment by lexman** [comment]
Hello,

I was already following my first idea (make this data a good complement for https://github.com/datasets/country-codes), so here is a datatapackage with only 2 fields. I called it geo-countries-110m as suggested above by @rgrp.
It's available on : http://sisyphus.lexman.org/workflows/geo-countries-110m/datapackage.json

Source code and doc are on github at https://github.com/lexman/geo-countries-110m

I'll add some fields later on, but I already know some are out of purpose, like population or gdp.

**Comment by rgrp** [comment]
@lexman this is brilliant. If it it looks good we'd move this over into github.com/datasets and make this an official core dataset!

@pdehaye + @jalbertbowden do you want to review.

**Comment by jalbertbowden** [comment]
@rgrp i'll take a peek tonight

**Comment by lexman** [comment]
For review :
* Validation link : http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Flexman%2Fgeo-countries-110m%2Fmaster%2Fdatapackage.json

Unfotunately, preview link does not seem to work properly : http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2Flexman%2Fgeo-countries-110m%2Fmaster%2Fdatapackage.json because the map is not displayed. It does not seem to be an issue with the datapackage, because I get an error a 'dataproxy' url from the viewer : http://data.okfn.org/tools/dataproxy/?url=https%3A%2F%2Fraw.githubusercontent.com%2Flexman%2Fgeo-countries-110m%2Fmaster%2Fdata%2Fcountries.geojson . Anyone an idea ? @rgrp ?

**Comment by rgrp** [comment]
@lexman when you get that 404 its because the underlying file does not exist which it does not ;-) You have `countries.geojson` in the resource path but the file is `countries.json` - https://github.com/lexman/geo-countries-110m/blob/master/data/countries.json

Also the homepage file should use http:// not git:// (it must be a url ...)

**Comment by lexman** [comment]
Thanks for the help, it's much better now !

**Comment by rgrp** [comment]
@lexman awesome - can you resubmit validation and preview links.

@pdehaye can you review and then do the honours re moving this over :-)

**Comment by pdehaye** [comment]
@rgrp  will try to start doing this in 10 hours or so. have been very busy past week

**Comment by jalbertbowden** [comment]
looks great! nicely done. thank you.

**Comment by lexman** [comment]
Validation link : http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Flexman%2Fgeo-countries-110m

Preview link : http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Flexman%2Fgeo-countries-110m

**Comment by pdehaye** [comment]
Hi @lexman, this looks good, except that I am a bit baffled at what you mean by 1:110m. I understand you mean some measure of how coarse the approximation is, but I have trouble translating the scale (1:110m) to a measure of the granularity of the approximation. 

Also, your README.md mentions 1:110, not 1:110m. And again, the homepages will need to be adapted to the new address once you transfer ownership.

**Comment by lexman** [comment]
@pdehaye, you're right about the scale : one has to master both geography and computers to understand what is means in pixels. So I removed every reference to the scale (except in the `sources`field) and I changed the name of the repository.

Here are the new links with the updated name :
* validation : http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Flexman%2Fgeo-countries
* preview : http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Flexman%2Fgeo-countries

Also I changed the references of the repository for hosting in the datasets organisation

**Comment by pdehaye** [comment]
@lexman Looks good! Can you transfer ownership?

**Comment by lexman** [comment]
Transfert should be complete :)

**Comment by rgrp** [comment]
@pdehaye would you like to explain to @lexman what last steps need to be done (e.g. add to core list, reload site, tweet it!) - that way @lexman can lead on this in future ;-) I think most of this is already in http://data.okfn.org/doc/core-data-curators#4-publishing

**Comment by pdehaye** [comment]
Hi @lexman 
The steps I take after validating, checking the dataset, etc, and the transfer of ownership (indeed these steps  are explained at http://data.okfn.org/doc/core-data-curators#4-publishing , slight update waiting in a pull request):
 *  Add to the [catalog list](https://github.com/datasets/registry/blob/master/catalog-list.txt) **and** the [core list](https://github.com/datasets/registry/blob/master/core-list.txt) **and** the associated csv files: [catalog-list.csv](https://github.com/datasets/registry/blob/master/data/catalog-list.csv) and [core-list.csv](https://github.com/datasets/registry/blob/master/data/core-list.csv). 
* Reload [http://data.okfn.org/data/](http://data.okfn.org/data/) by visiting <http://data.okfn.org/admin/reload/>
* Tweet from the @OKFNLabs account a link to the http://data.okfn.org/data/ page for the dataset. For this you need to get access, which you don't have right now. @danfowler , can you give @lexman access if that's ok? 
 * Close the issue
