### ISSUE TITLE
NUTS Administrative Boundaries

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#43]

**Comment by ThomasG77** [comment]
Waiting but I'm interested: it's geodata dataset and I do GIS.
Which level is wanted for NUTS?
We can already use http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units except if licence is not OK (not sure about his, not a lawyer).

**Comment by rgrp** [comment]
@ThomasG77 what levels are available for NUTS (I'm not an expert either). Re the license: we will sometimes live with a restrictive license (see e.g. ISO codes) but we will prominently note it and make clear that the data package license (if an open one) only applies to our efforts in packaging and that underlying data may have different and more restrictive rights that affect the data package.

Could you give more detail here on LAU ...

**Comment by rgrp** [comment]
@ThomasG77 are you interested in taking on - this would be a nice one to do.

**Comment by ThomasG77** [comment]
I will begin to work on it. We may need to work on NUTS population overall instead of UK only e.g #51

**Comment by rgrp** [comment]
@ThomasG77 how are you doing here - note this is NUTS boundaries *not* populations per NUTS area

**Comment by ThomasG77** [comment]
I will do it this week (end of the week because already busy before)

**Comment by ThomasG77** [comment]
After a long time, it's done...
See my repository at https://github.com/ThomasG77/geo-nuts-administrative-boundaries

Feedback welcome (PS: already good for [validation](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2FThomasG77%2Fgeo-nuts-administrative-boundaries%2Fmaster%2Fdatapackage.json) and [visualisation](http://data.okfn.org/tools/view?url=https%3A%2F%2Fraw.githubusercontent.com%2FThomasG77%2Fgeo-nuts-administrative-boundaries%2Fmaster%2Fdatapackage.json)) before I give ownership to @datasets/owners

**Comment by rgrp** [comment]
@ThomasG77 great job and thanks for the persistence!

@Yannael are you happy to review?

**Comment by Yannael** [comment]
@ThomasG77 @rgrp 

Nice! Data format and view seem good.

I could not run the code though. 
* Dependency shelljs is missing
* Folder data must be created by hand
* and then get an error 

"debug(drivers.prototype.getNames());                            
TypeError: Illegal invocation"

that I could not fix

Also,  
* I suggest you put the code (index.js and package.json) in a separate 'scripts' directory.
* you may add the 'contributors' and 'maintainers' fields if you wish to keep responsibility for the package. 

Thanks!

**Comment by ThomasG77** [comment]
@Yannael 

Due to your feedback, I've done the changes:
* to move `index.js` and `package.json` to `scripts` directory
* to add "contributors" and "maintainers" fields in `datapackage.json`


Also, I don't have any issue with "debug(drivers.prototype.getNames());"
Can you provide your system? On my side, for info, my OS is Ubuntu 14.04 64bits.

**Comment by Yannael** [comment]
@ThomasG77 
Ok great

Regarding the issue with the code, my system is Mac OS X 10.7.5, and I have node.js v0.12.0 

The complete error message is 

```
/Users/yalb/Downloads/geo-nuts-administrative-boundaries-master/scripts/index.js:94
    debug(drivers.prototype.getNames());
                            ^
TypeError: Illegal invocation
    at Request.<anonymous> (/Users/yalb/Downloads/geo-nuts-administrative-boundaries-master/scripts/index.js:94:29)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/yalb/Downloads/geo-nuts-administrative-boundaries-master/scripts/node_modules/request/request.js:1167:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

Maybe this is a platform dependent issue, and I am not sufficiently acquainted to node.js to fix it 

@rgrp What do think, ok to move to core repository?

**Comment by ThomasG77** [comment]
@Yannael Can you remove the line doing `debug(drivers.prototype.getNames());` on your local side and try again?
This line was for learning purpose, so if it only fails here because of OS, it would be worth removing IMO.

**Comment by Yannael** [comment]
@ThomasG77 @rgrp 

Commenting out the line is enough indeed, it runs fine now, great!

**Comment by ThomasG77** [comment]
I've done changes in the code to fix issue and in the README.md description for the script path.
The ownership has been changed too and the repo is currently at https://github.com/datasets/geo-nuts-administrative-boundaries The only thing we may change now could be the repository name? Other opinions @rgrp @Yannael

**Comment by Yannael** [comment]
Nice, I updated catalog and core lists. The repository name is good for me

**Comment by lexman** [comment]
Hello, 

has this dataset been published yet ?

**Comment by rgrp** [comment]
Good question. The answer is yes: http://data.okfn.org/data/core/geo-nuts-administrative-boundaries

**Comment by rgrp** [comment]
FIXED. This is done and live at http://data.okfn.org/data/core/geo-nuts-administrative-boundaries and https://github.com/datasets/geo-nuts-administrative-boundaries

**Comment by rgrp** [comment]
@pdehaye can we get this tweeted?

**Comment by pdehaye** [comment]
@rgrp done, tweeted

**Comment by danfowler** [comment]
:+1:
