### ISSUE TITLE
Stock Symbols List - US

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#52]
A complete list of all NYSE stock symbols (plus company name).

TODO: work out what symbol list(s) we want.

Note EDGAR also have a symbol list: http://okfnlabs.org/blog/2014/03/04/sec-edgar-database.html plus see bloomberg list in #25

**Comment by joehand** [comment]
I created a [data package](https://github.com/joehand/nasdaq-nyse-listings) for this using data available on NASDAQ's FTP (see readme). First time making a data package, let me know if I missed something.

There are a two datasets available on the FTP NASDAQ listings and all other listing. I made a separate fine for just the NYSE listings (from the other dataset).

**Comment by joehand** [comment]
Oh a few questions too:

* I couldn't find anything about the data license on the NASDAQ site.  Is there a suggested license for the data?
* NASDAQ provides the file creation time but I didn't see that in the datapackage.json schema. Is that something that would be useful to keep track of?

**Comment by rgrp** [comment]
@joehand can you clarify if you just have the nasdaq symbols. I'm starting to think we may want multiple files or even multiple data packages.

I've also updated the description to reflect this todo.

**Comment by rgrp** [comment]
@joehand any developments here? We can do multiple packages here if needed.

**Comment by joehand** [comment]
@rgrp, NASDAQ separates out the data into two files, *NASDAQ-Listed Securities* and *Other Exchange-Listed Securities*, as seen [here](http://www.nasdaqtrader.com/trader.aspx?id=symboldirdefs) in the documentation. 

The NYSE is a subset in the *Other Exchange-Listed Securities*. There are four exchanges included in the *Other Exchange-Listed Securities*:

* NYSE MKT
* New York Stock Exchange (NYSE)
* NYSE ARCA
* BATS Global Markets (BATS)

It seems we should at least follow NASDAQ separation and have two separate packages (NASDAQ and Other). I don't know enough about the *Other Exchange-Listed Securities* to say whether those should be also separated.

**Comment by rgrp** [comment]
@joehand sounds good. Do you want to make a start with whatever is easiest and we go from there.

**Comment by rgrp** [comment]
@joehand how are you doing here? Let's do the simplest thing possible and then add more later.

/cc @Yannael

**Comment by joehand** [comment]
@rgrp I updated the [original repo](https://github.com/joehand/nasdaq-nyse-listings) to just have NASDAQ data and I added [another repo](https://github.com/joehand/nyse-listings) for the *Other Listings* (which includes a filtered file for NYSE only).

**Comment by rgrp** [comment]
@joehand this is great. Are you happy to commence the process for getting into core? see http://data.okfn.org/doc/core-data-curators#3-quality-assurance

/cc @Yannael

**Comment by joehand** [comment]
QA For [NASDAQ Package](https://github.com/joehand/nasdaq-listings): 
* [Validation](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjoehand%2Fnasdaq-listings%2Fmaster%2Fdatapackage.json)
* [View](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fjoehand%2Fnasdaq-listings)

QA for [NYSE/Other Package](https://github.com/joehand/nyse-listings):
* [Validation](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fraw.githubusercontent.com%2Fjoehand%2Fnyse-listings%2Fmaster%2Fdatapackage.json)
* [View](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fjoehand%2Fnyse-listings)

**Comment by rgrp** [comment]
@Yannael are you able to review this to see if we can get this in?

**Comment by Yannael** [comment]
@joehand @rgrp 
Sorry for the late review, I had missed it from the queue.
Nice, a couple of changes to make:
* For the License, a link should be made to their Copyright page http://www.nasdaqtrader.com/Trader.aspx?id=CopyDisclaimMain. I would suggest using the same Licensing as https://github.com/datasets/geo-nuts-administrative-boundaries#license, adapting the copyright notice link to the Nasdaq page.
* For the datapackage.json
 * in NASDAQ package. The name should be changed to "nasdaq-listings"
 * For both packages, adding the sources and licenses fields would be nice (see for example https://github.com/datasets/geo-nuts-administrative-boundaries/blob/master/datapackage.json)

I can take care of making these changes to speed up the integration of these packages in the core repository. 

Can you finally transfer the ownership of both repos to the 'datasets' organization?

Thanks!

**Comment by joehand** [comment]
@Yannael great, I transferred the NYSE repo. It looks like you already have a nasdaq-listing repo, so I can't transfer that one (I tried renaming and that didn't work either). Let me know when you delete the other repo and I can transfer it.

Thanks.

**Comment by Yannael** [comment]
@joehand deleted, can you retry?

**Comment by joehand** [comment]
@Yannael worked this time! Let me know if there is anything else I can help on. Thanks for your help!

**Comment by Yannael** [comment]
@joehand Great! I'll make the couples of changes mentioned above, and transfer. I let you know when done. Thanks for the contributions!

**Comment by Yannael** [comment]
@rgrp @joehand Transferred
