### ISSUE TITLE
Property Prices (Around the World)

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#55]
This issue is about a consolidated set of data (probably at a coarser granularity e.g. country level averages per month or per year).

- [ ] Consolidated - BIS have good consolidate data here (openness isn't super clear). http://www.bis.org/statistics/pp.htm
  - Data file: http://www.bis.org/statistics/pp/pp.xlsx
  - long time series: http://www.bis.org/statistics/pp_long.htm

**Focus on a consolidated global dataset -- see if any other options than BIS**

##  Country Specific

*These will be separate issues*

Here for reference
- [x] UK - various data series - https://github.com/datasets/house-prices-uk
- [x] US - Case/Shiller series - https://github.com/datasets/house-prices-us
- [ ] ...

Interesting paper with long run time series across the world: http://voxeu.org/article/home-prices-1870 - however no data link afaict.

**Comment by PilipMac** [comment]
Any interest in Ireland? I could put that together for you.

**Comment by rgrp** [comment]
@PilipMac definitely interested in ireland - could you open a specific issue for irish property prices.

**Comment by rgrp** [comment]
@PilipMac any news here?

**Comment by rgrp** [comment]
@sxren interested in taking a look at this one?

**Comment by lexman** [comment]
For France a lot of data can be found here : http://www.cgedd.developpement-durable.gouv.fr/prix-immobilier-evolution-a-long-terme-a1048.html

Including prices in Paris since 1200 : http://www.cgedd.developpement-durable.gouv.fr/prix-immobilier-evolution-a-long-terme-a1048.html

**Comment by scls19fr** [comment]
This Python script might help to download files for each department:


```python
#!/usr/bin/env python

import requests
import os.path
import shutil

def download_files():
    lst = [
        ("01", "ain"), 
        ("02", "aisne"), 
        ("03", "allier"), 
        ("05", "hautes-alpes"), 
        ("04", "alpes-de-haute-provence"), 
        ("06", "alpes-maritimes"), 
        ("07", "ardeche"), 
        ("08", "ardennes"), 
        ("09", "ariege"), 
        ("10", "aube"), 
        ("11", "aude"), 
        ("12", "aveyron"), 
        ("13", "bouches-du-rhone"), 
        ("14", "calvados"), 
        ("15", "cantal"), 
        ("16", "charente"), 
        ("17", "charente-maritime"), 
        ("18", "cher"), 
        ("19", "correze"), 
        ("2A", "corse-du-sud"),
        ("2B", "haute-corse"), 
        ("21", "cote-d'or"), 
        ("22", "cotes-d'armor"), 
        ("23", "creuse"), 
        ("24", "dordogne"), 
        ("25", "doubs"), 
        ("26", "drome"), 
        ("27", "eure"), 
        ("28", "eure-et-loir"), 
        ("29", "finistere"), 
        ("30", "gard"), 
        ("31", "haute-garonne"), 
        ("32", "gers"), 
        ("33", "gironde"), 
        ("34", "herault"), 
        ("35", "ille-et-vilaine"), 
        ("36", "indre"), 
        ("37", "indre-et-loire"), 
        ("38", "isere"), 
        ("39", "jura"), 
        ("40", "landes"), 
        ("41", "loir-et-cher"), 
        ("42", "loire"), 
        ("43", "haute-loire"), 
        ("44", "loire-atlantique"), 
        ("45", "loiret"), 
        ("46", "lot"), 
        ("47", "lot-et-garonne"), 
        ("48", "lozere"), 
        ("49", "maine-et-loire"), 
        ("50", "manche"), 
        ("51", "marne"), 
        ("52", "haute-marne"), 
        ("53", "mayenne"), 
        ("54", "meurthe-et-moselle"), 
        ("55", "meuse"), 
        ("56", "morbihan"), 
        ("57", "moselle"), 
        ("58", "nievre"), 
        ("59", "nord"), 
        ("60", "oise"), 
        ("61", "orne"), 
        ("62", "pas-de-calais"), 
        ("63", "puy-de-dome"), 
        ("64", "pyrenees-atlantiques"), 
        ("65", "hautes-pyrenees"), 
        ("66", "pyrenees-orientales"), 
        ("67", "bas-rhin"), 
        ("68", "haut-rhin"), 
        ("69", "rhone"), 
        ("70", "haute-saone"), 
        ("71", "saone-et-loire"), 
        ("72", "sarthe"), 
        ("73", "savoie"), 
        ("74", "haute-savoie"), 
        ("75", "paris"), 
        ("76", "seine-maritime"), 
        ("77", "seine-et-marne"), 
        ("78", "yvelines"), 
        ("79", "deux-sevres"), 
        ("80", "somme"), 
        ("81", "tarn"), 
        ("82", "tarn-et-garonne"), 
        ("83", "var"), 
        ("84", "vaucluse"), 
        ("85", "vendee"), 
        ("86", "vienne"), 
        ("87", "haute-vienne"), 
        ("88", "vosges"), 
        ("89", "yonne"), 
        ("90", "territoire-de-belfort"), 
        ("91", "essonne"), 
        ("92", "hauts-de-seine"), 
        ("93", "seine-saint-denis"), 
        ("94", "val-de-marne"), 
        ("95", "val-d'oise"), 
        # ("976", "mayotte"), 
        ("971", "guadeloupe"), 
        ("973", "guyane"), 
        ("972", "martinique"), 
        ("974", "reunion")
    ]

    errors = 0
    for i, (num, dept) in enumerate(lst):
        filename = "immobilier-%s-%s.xls" % (dept, num)
        url = "http://www.cgedd.fr/valeur-immobilier-departement/%s" % filename
        if not os.path.isfile(filename):
            print("%03d - Downloading %s" % (i+1, url))
            r = requests.get(url, stream=True)
            if r.status_code == 200:
                with open(filename, 'wb') as f:
                    r.raw.decode_content = True
                    shutil.copyfileobj(r.raw, f)
            else:
                print("status_code is %d - skipping" % r.status_code)
                errors += 1
        else:
            print("%03d - File '%s' was downloaded previously - skipping" % (i+1, filename))
    print("Downloaded %d files with %d errors" % (i+1, errors))

def main():
    download_files()

if __name__ == "__main__":
    main()
```

processing may also be done using Python Pandas to output "raw" csv files

**Comment by rgrp** [comment]
@lexman or @scls19fr  this is great. Can you boot a specific issue for France and copy this info over into the description.

**Comment by scls19fr** [comment]
This script can also help to find xls, xlsx, csv links

```python
from bs4 import BeautifulSoup
import requests

url = "http://www.cgedd.developpement-durable.gouv.fr/prix-immobilier-evolution-a-long-terme-a1048.html"
r = requests.get(url)
html = r.content
soup = BeautifulSoup(html)
i = 0
for link in soup.findAll("a"):
    href = link.get("href")
    if href is not None:
        for ext in [".xls", ".xlsx", ".csv"]:
            if ext in href:
                i += 1
                print(href)
print("%03d links found" % i)
```

**Comment by rgrp** [comment]
@zelima could you start looking at the BIS data on this one and scripting the data extraction.

**Comment by zelima** [comment]
@rgrp I went through BIS data, main file is constructed like this:
* The data contains Monthly, quarterly, half-yearly and yearly data. form 31-01-1966 to 31-05-2016. _which one do we need, or all of them?_
* For several countries there may be several data e.g: United Kingdom has two different data depending on Compiling agency (national statistic office and private sector), other countries may have more then two. e.g.: Finland has 7 depending on various options. _We need all of them or one of them?_
* Also 100 units for different countries may be different year - most of them are 2010, but there are exceptions e.g: For same UK it is 2002 and 1983
```
date,UK national stat office, UK private sector
,2002 = 100 (Units),1983 = 100 (Units)
28-02-2002,100,324.3
31-03-2002,103.5,329.2
30-04-2002,104.9,335.9
```

**Comment by rgrp** [comment]
@zelima how big are the files. Can you give a short list here of the actual *files* involved with their size.

**Comment by zelima** [comment]
There is only one file with 6 sheets, first two sheets are content and documentation, other four - monthly, quarterly, half-yearly and anyal series. The file is not too big (500 KB).

Size of excel sheets (rows/cols)
* Monthly Series - 609/53
* Quarterly Series - 249/220
* Half-yearly Series - 24/5 (there's something wrong with this one - it contains only Greece)
* Annual - 201/29

**Comment by rgrp** [comment]
@zelima can you boot a repo for this and create the readme and add the archive files (in an automated way using a `scripts` file).

Based on what you have shown me I think we would do all temporal granularities and name as per our standard naming conventions. I would start though with annual data first.

Can you set out here or in the README what the structure of the *output* data file would be?

**Comment by zelima** [comment]
@rgrp The repository with README describing structure of output data is ready: https://github.com/zelima/house-prices-global

**Comment by rgrp** [comment]
@pdehaye could you take a look and review this repo prepared by @zelima ?

**Comment by rgrp** [comment]
Interesting paper with long run time series across the world: http://voxeu.org/article/home-prices-1870 - however no data link afaict.

**Comment by pdehaye** [comment]
Hi @zelima. I just had a look at your suggestion. I am not sure I agree with the proposal. It would mix just by country, which would merge columns that have nothing to do with each other (different payment plans, if I understand right). This would mess up some of the datapackage tools (like automated graphing). 
I suggest you keep the columns separate, and go for something like `NO_annual_A:NO:2:1:0:0:1:0.csv` for a typical name. This file would simply contain:

```
31.12.1841, 0.1231
31.12.1842, 0.1058
31.12.1843, 0.1138
...
```
Ideally the documentation file would be extended to include an explicit reference to the file name, and a column giving explicitly the frequency of payment.

**Comment by AcckiyGerman** [comment]
Temp repo: https://github.com/AcckiyGerman/global-house-prices-selected
Done:
* analyse
* find nice source
* output format
Todo:
* pivot table
* update datapackage.json['resources']
* push to datahub.io

**Comment by rufuspollock** [comment]
@AcckiyGerman can you comment on https://github.com/zelima/house-prices-global - is that useful or not? /cc @zelima

**Comment by AcckiyGerman** [comment]
Hi, @zelima I think you can remove https://github.com/zelima/house-prices-global now, coz I found the csv source on the http://bis.org, so there is no need to parse xlsx any more. Thanks.

**Comment by rufuspollock** [comment]
@AcckiyGerman i'm not asking for @zelima to remove it - i'm more wondering on what the difference was and whether his existing work and structure were useful.

**Comment by AcckiyGerman** [comment]
the repo in the datasets https://github.com/datasets/global-house-prices

**Comment by AcckiyGerman** [comment]
The data package is ready, please review! @zelima @Mikanebu 
https://github.com/datasets/global-house-prices

@rufuspollock 
This https://github.com/zelima/house-prices-global repo from Irakli was useful on the analyse stage.
The differences between Irakly repo and my one is:
* source in csv was found - no need to parse xlsx
* the original table from bis.org (both xlsx and csv) has  date and country info in orthogonal to each other, the Irakly propose was to put it alongside, witch leads to mixing all other info in a table (there also is important info like "Unit of measure", "Value" which we don't want to lost.
* in my case I just pivoted the table and save all additional data as 'unit, 'value', 'country' in a datapackage.json

The original table from bis has complex structure, and there could be several ways to convent it, or even leave it like it is.
So while I have no experience how this data could be used - I can't decide this question.
So I ask you to review the table in 'archive/...csv' and result one and a datapackage.json and give me a feedback please.

**Comment by AcckiyGerman** [comment]
The required Property Prices dataset is there: https://github.com/datasets/global-house-prices , which includes 59 countries and generalized prices for developing and advanced markets. Reviews and verified. We could now close this issue, aren't we?

**Comment by AcckiyGerman** [comment]
The result [dataset](https://github.com/datasets/global-house-prices) is updated:
* data is divided onto 4 files
* table is unpivoted
@rufuspollock please could you review the dataset and close this issue if it is ok.

**Comment by rufuspollock** [comment]
@AcckiyGerman following standard naming practice this should have been called `house-prices` or `house-prices-global` (/cc @zelima). Please can you get this corrected both in the github repo and on datahub.

**Comment by zelima** [comment]
Structure of dataset was discussed here https://github.com/datasets/global-house-prices/issues/2 and reviewed. So yes, we can close

**Comment by AcckiyGerman** [comment]
FIXED
Datapackage has been moved there: https://github.com/datasets/house-prices-global
Also it will be uploaded to datahub.io https://github.com/datasets/house-prices-global/issues/1

**Comment by rufuspollock** [comment]
General discussion on property prices around the world continues in the new awesome repo here: https://github.com/datahq/awesome-data/issues/9
