### ISSUE TITLE
CO2 PPM data

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#56]
CO2 parts per million data

See http://www.esrl.noaa.gov/gmd/ccgg/trends/index.html

**Comment by rgrp** [comment]
Started work (but very incomplete - e.g. no data): https://github.com/datasets/co2-ppm

Reference: https://github.com/datasets/co2-fossil-global

**Comment by sxren** [comment]
Packaged.

**Comment by rgrp** [comment]
@sxren perfect - can you link the data package github repo here - then we'll close.

**Comment by sxren** [comment]
The data package github repo can be found at https://github.com/datasets/co2-ppm.

Hmm. There isn't a `Close issue` button next to the `Comment` button. Maybe I don't have permission to close the issue.

**Comment by rgrp** [comment]
FIXED.

@sxren I've made you admin on this repo so you'll now see the close button too! Welcome to being a Core Data "Queue Manager" :-)

**Comment by rgrp** [comment]
@sxren live at http://data.okfn.org/data/core/co2-ppm

BTW: one last comment - I think title could be sharpened a bit to exclude acronym's like ESRL. I'd go for something like: "CO2 PPM - Concentration of Atmospheric Carbon Dioxide Over Time"

**Comment by sxren** [comment]
@rgrp wow! very cool. thank you.

comments and corrections welcome. i changed the title in the data package to your suggestion.
