### ISSUE TITLE
Language codes (ISO 639)

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#58]
Nice little dataset

* Source: http://www.iso.org/iso/home/standards/language_codes.htm
* Suggested name: `language-codes`
* Suggested title: Language Codes (ISO 639)
* Suggest we want 2 digit and 3 digit codes (probably separate files?)

**Comment by hirntodt** [comment]
Iso.org charge for the download, but link to the library of congress as Registration Authority for this ISO. They again provide a file for download.
http://www.loc.gov/standards/iso639-2/iso639jac.html

I would take this on as a first project for packaging, unless someone stops me..

**Comment by rgrp** [comment]
@hirntodt all sounds good and you are hereby the current assignee of this packaging work :-)

**Comment by hirntodt** [comment]
ok, I have packaged the data, put it on https://github.com/hirntodt/okfn-language-codes . 
Now I am confused on how to proceed (new to the pull request business).

Any pointers ?

**Comment by rgrp** [comment]
Next steps:

- Quality check
- Move to github.com/datasets
- Add to core datasets list

Re quality check:

- Check datapackage.json in http://data.okfn.org/tools/validate (you may need raw link)
- Try to view it here - http://data.okfn.org/tools/view

**Comment by hirntodt** [comment]
I can not validate using the validator tool (even the json from the generator tool does not pass).
The view however looks fine : 

http://data.okfn.org/tools/view?url=http%3A%2F%2Fhirntodt.de%2FOKFN-core-datasets%2FISO639%2Fdatapackage.json

As the file is rather  small i put both codes in there, it also seems more handy for doing conversions between them.

**Comment by rgrp** [comment]
@hirntodt can you link the validator result (you can just copy and paste the url).

Aslo I'm wondering what would be most useful to users. Do you think users might prefer 2 files:

- One file just of 2 digit codes and english name
- One file which is everything (what we have)

I'm wondering as I imagine many people just want the 2 digit codes so providing that so they can just "get it" fast is probably useful.

In addition could you give a bit more detail either in README or description of columns about the terminologic codes (what is it? why would one that as well as the bibliographic codes ...)

**Comment by hirntodt** [comment]
I included a short, 2 letter code version for quick and easy matching of languages with their code and vice versa.
The full list with all 3 different codes is a  second file now in the package. 

Also extended the README.

[Viewer](http://data.okfn.org/tools/view?url=http%3A%2F%2Fhirntodt.de%2FOKFN-core-datasets%2FISO639%2Fdatapackage.json#readme)

[The validator still fails]
(http://data.okfn.org/tools/validate?url=http%3A%2F%2Fwww.hirntodt.de%2FOKFN-core-datasets%2FISO639%2Fdatapackage.json)

**Comment by rgrp** [comment]
@hirntodt this is great! Looking good to get this in and a new official core data package :-)

re the validator message, does that make sense to you? What it is saying is the data package name field is invalid as it needs to be lowercase alphanumeric ... (any suggestions on how to improve the validator feedback warmly welcome at https://github.com/okfn/data.okfn.org/issues :-) ...)

**Comment by hirntodt** [comment]
No, the message does not make sense to me :) 

So, how  will the package find its way into https://github.com/datasets ?

**Comment by rgrp** [comment]
So the message says (with comments from me to explain better):

```
[
  {
    "message": "String does not match pattern: ^([a-z0-9\\.\\_\\-])+$",  # this is what wrong with the field value
    "code": 202,
    "dataPath": "/name",  # this is the path in the datapackage.json - so "name" field
    "schemaPath": "/properties/name/pattern",
    "subErrors": null,
    "type": "schema"
  }
]
```

Re finding it way in here - that requires you to transfer ownership across (think that will require you to make a relevant person an admin on that repo). We can come to that once we have finalized and checked the datapackage.

**Comment by hirntodt** [comment]
@rgrp, small misunderstanding on my side. It didn't make sense to me bcause all the "name" tags in the schema were matching the pattern, no matter how often I doublechecked. Took just a weeks break to figure it was the top level tag not matching...

Anyway, it [validates now](http://data.okfn.org/tools/validate?url=http%3A%2F%2Fwww.hirntodt.de%2FOKFN-core-datasets%2FISO639%2Fdatapackage.json)

And if the split into two files and description are reasonable, I think it's good to go.
[Viewer preview](http://data.okfn.org/tools/view?url=http%3A%2F%2Fhirntodt.de%2FOKFN-core-datasets%2FISO639%2Fdatapackage.json)

**Comment by rgrp** [comment]
Great. Looks good to go. Could you make me an admin on the repo in github so I can move it to github.com/datasets. We'll then do the last steps of adding to the list and then on the site.

**Comment by hirntodt** [comment]
ok, done.

**Comment by rgrp** [comment]
@hirntodt sorry for slight delay - had to move from private account to /datasets/.

All looks great and this now added to the Core Datasets list and is live at:

https://github.com/datasets/language-codes
http://data.okfn.org/data/core/language-codes

Congratulations on packaging your first official core dataset!
