### ISSUE TITLE
US CPI data

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#64]
Already have Data Package here:

https://github.com/datasets/cpi-us

But:

* Needs a maintainer (someone to make sure it is up to date month after month) - may need to look at automating
* Need to check this is best data possible - are there alternative sources
* Need to think about how to handle revisions (if they happen here)

**Comment by seiteta** [comment]
I volunteer to maintain this package as a first project if it's OK for everyone.

**Comment by rgrp** [comment]
@seiteta that's fantastic.

**Comment by rgrp** [comment]
@seiteta are you also up for researching on those questions listed in the main part of this issue and reporting either here, or perhaps better, moving this discussion to the issues on the us-cpi repo.

**Comment by seiteta** [comment]
@rgrp yes, for sure, I would like to maintain this package and look for alternative sources!

**Comment by rgrp** [comment]
@seiteta great - i'm going to close this issue and if you could open an issue on the cpi-us repo about researching sources that would be great.

**Comment by rgrp** [comment]
FIXED. Running and we have a maintainer.

**Comment by seiteta** [comment]
@rgrp Done!
