### ISSUE TITLE
UK Crime data

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#7]
https://github.com/datasets/crime-uk

Does this merit inclusion?

**Comment by pdehaye** [comment]
I don't think it does. Either because other packages are more worthy of the effort of finding a maintainer, or because it is geographically fairly limited and as such not core.

**Comment by pdehaye** [comment]
I don't think it does. Either because other datasets are more worthy of the effort of finding a maintainer, or because it is geographically limited and as such not core.

**Comment by rgrp** [comment]
WONTFIX. I agree. Closing as WONTFIX.
