### ISSUE TITLE
United Kingdom Standard Industrial Classification of Economic Activities (SIC)

### ISSUE THREAD

**Issue by ekoner** [datasets/registry#71]
The UK SIC codes are used to classify businesses and other economic activities. The codes can be found on gov.uk but licensing is unclear. The codes are published as [pdf](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/376462/condensedSICList.pdf), there may be other formats available.

No SIC codes appear in the search and as I'm working on companies house data, this would be very useful for me and others in CSV format.

**Comment by rgrp** [comment]
@ekoner great suggestion. Would you be up for taking on packaging here?

**Comment by rgrp** [comment]
By the way if you are looking for way to parse PDF check out https://github.com/okfn/ideas/issues/52

**Comment by ekoner** [comment]
@rgrp Yes, I will. Thanks for the link.

**Comment by sxren** [comment]
@ekoner csv format https://github.com/nathanpitman/sic-codes/blob/master/2007/sic_codes.csv

**Comment by ekoner** [comment]
Thanks @sxren, I'd already parsed the pdf as an excuse to play with OpenRefine. That link heped me cross-check my work!

**Comment by sxren** [comment]
@ekoner you're very welcome. :) glad i didn't stunt your learning. and it was kind of you to find a use for it.

**Comment by ekoner** [comment]
It's been a long week chasing down licensing information for this dataset. While I'm still waiting for a reply direct from Companies House, I'm inclined to mark this as open data or at least public data based on information kindly provided by [Owen Boswarva](https://twitter.com/owenboswarva/status/566327126719463424). 

The SIC codes used by Companies House are a subset of the codes published by the ONS whose [copyright page](http://www.ons.gov.uk/ons/site-information/information/creative-commons-license/index.html) supports an assumption of open data and requests attribution:

Users reproducing ONS content which is adapted should include a source accreditation to ONS: Adapted from data from the Office for National Statistics licensed under the Open Government Licence v.3.0.

**Comment by rgrp** [comment]
@ekoner well done on tracking down licensing info and we can include that in the README.md

What do you need in terms of a steer on making the data package? I suggest we'll make this tabular data (i.e. in CSV) and there are instructions here you can follow: http://data.okfn.org/doc/publish (feedback and improvements on those docs are very welcome).

**Comment by ekoner** [comment]
Thanks @rgrp 
Questions about the data package creator:
1. I've named the file sic-2007-condensed.csv - does this meet naming conventions and where can I find these?
2. Title - Again, is there a naming convention for this? I've gone with "UK condensed standard industrial classification of economic activities (SIC) 2007 codes"
3. Name - Same as title? Abbreviated? I've used "UK Condensed SIC 2007"
4. License - Can't select or type in, so I'm assuming it goes somewhere else.
5.  "mediatype": "application/vnd.ms-excel" - I think this is incorrect - shouldn't it be csv?

**Comment by sxren** [comment]
@ekoner 

1.your name follows the conventions i've seen practiced (lowercase, dash delimited). i don't know if they're documented. @rgrp http://dataprotocols.org/simple-data-format/ is down.
1. title: convention seems to be concise, title case: e.g., `UK SIC 2007 Codes`? more information can be provided in a description field.
1. name: lowercase, concise, dash delimited: e.g., uk-sic-2007, uksic
1. license: would you be comfortable adding it to the json by hand for now? @rgrp is there anything i can do to get the update deployed?
1. mediatype: yes, it should be `text/csv`

**Comment by ekoner** [comment]
Right, just stuck validating the [json file](https://www.dropbox.com/s/ff12urpx3zn9rfr/datapackage.json?dl=0). Unsure if Dropbox is adding some rubbish to the file or I've made an error editing.

**Comment by sxren** [comment]
@ekoner 
use:
https://www.dropboxusercontent.com/s/ff12urpx3zn9rfr/datapackage.json?dl=1
(or https://dl.dropboxusercontent.com/s/ff12urpx3zn9rfr/datapackage.json)

changing `dl=0` to 'dl=1` or replacing `www` with `dl` gives you the raw link to the file.

a comma is missing at the end of the description line.

**Comment by ekoner** [comment]
Thanks @sxren - I've fixed that one and now getting `[SCHEMA] String does not match pattern: ^([a-z0-9\.\_\-])+$`. Any ideas?

**Comment by sxren** [comment]
@ekoner See my comment in https://github.com/datasets/registry/issues/71#issuecomment-74420232 above about the name. `3`.

**Comment by ekoner** [comment]
Thanks so much @sxren! Now valid:

[Validation Link](http://data.okfn.org/tools/validate?url=https%3A%2F%2Fdl.dropboxusercontent.com%2Fs%2Fff12urpx3zn9rfr%2Fdatapackage.json)
[View Link](http://data.okfn.org/tools/view?url=https%3A%2F%2Fdl.dropboxusercontent.com%2Fs%2Fff12urpx3zn9rfr%2Fdatapackage.json)

Do I need to publish now?

**Comment by sxren** [comment]
@ekoner oh, cool! your csv is being read. so, you answered my question from https://github.com/okfn/data.okfn.org/issues/153#issuecomment-74619064. :smiley_cat:

1. are the files in a public folder?
2. the mess at the top of the view is usually a result of not having a README.md in the data package folder. is there a README.md in the folder? if not, would you mind adding one? thanks!

**Comment by sxren** [comment]
@ekoner oh, no. my bad. the csv is not being read. :frowning:

**Comment by sxren** [comment]
@ekoner would you be cool with putting your data package on github?

**Comment by ekoner** [comment]
@sxren no worries, I've created a [repo](https://github.com/openyorkshire/uk-sic-2007-condensed).

**Comment by sxren** [comment]
@ekoner awesome! would you transfer that to datasets and then add the transferred repo (https://github.com/datasets/uk-sic-2007-condensed) to https://github.com/datasets/registry/blob/master/core-list.txt and https://github.com/datasets/registry/blob/master/catalog-list.txt ? thank you!

**Comment by ekoner** [comment]
All done @sxren - could you sanity check for me?

Cheers

**Comment by sxren** [comment]
@ekoner your dataset is up at http://data.okfn.org/data/core/uk-sic-2007-condensed :)

* i added the data directory to the path of the resource.
* i removed the file extension from the resource name—i missed that before.

this issue is closed. thank you very much!
