### ISSUE TITLE
Natural Gas Prices

### ISSUE THREAD

**Issue by rufuspollock** [datasets/registry#72]
Standard (US) natural gas prices and maybe north sea too
- Henry Hub

Stub repo in progress here with links to source data: https://github.com/datasets/natural-gas-prices

**Packager wanted!**

Similar one for gold already done: https://github.com/datasets/gold-prices

**Comment by zelima** [comment]
@rgrp I'll finish this one.

the output files will be: 
natural-gas-price-daily.csv
natural-gas-price-monthly.csv

daily
```
date,price
1997-01-07,3.82
1997-01-08,3.8
1997-01-09,3.61
1997-01-10,3.92
1997-01-13,4.0
1997-01-14,4.01
```
monthly
```
date,price
1997-01-01,3.45
1997-02-01,2.15
1997-03-01,1.89
1997-04-01,2.03
1997-05-01,2.25
```

**Comment by rgrp** [comment]
@zelima perfect. Let's get this one done.

**Comment by zelima** [comment]
@rgrp please review

validate link: http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fzelima%2Fnatural-gas-prices

view link: http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fzelima%2Fnatural-gas-prices

I Registered pull request for repository.

**Comment by rgrp** [comment]
@zelima can you link the pull request.

@lexman would you like to review this one?

**Comment by lexman** [comment]
@rgrp @zelima  I'll review it, but I need a few days... Sorry

**Comment by rgrp** [comment]
@lexman no problem - thanks!

**Comment by zelima** [comment]
Link for PR: https://github.com/datasets/natural-gas-prices/pull/1

**Comment by lexman** [comment]
Hello, 

@zelima I've started to review the PR and every thing looks good so far except for two minor things :
* file ``scripts/README.md~`` seam to be an artefact from your editor... It should be removed
* Makefile should be in the script directory

Unfortunately, I can't use the view link for a definite check because the server seams broken :
> Application Error
> An error occurred in the application and your page could not be served. Please try again in a few moments.
> If you are the application owner, check your logs for details.

 @rgrp do you have any idea ?

**Comment by lexman** [comment]
Well, the viewer is back and the data is great ! I really like the graph view @zelima

I'll merge the PR as soon as both corrections are made...

**Comment by zelima** [comment]
@lexman done: https://github.com/zelima/natural-gas-prices/commits/master

**Comment by lexman** [comment]
I merged the PR. Great work @zelima !

**Comment by lexman** [comment]
It seams that the natural-gas-prices has never been added to the core datasets...

I created a PR ( https://github.com/datasets/registry/pull/178 ) to add it to the main site. @pdehaye /cc @rgrp would you merge my PR ? I hope it is correct this time...

**Comment by lexman** [comment]
Thanks @rgrp , it works !

I think the next step is to tweet about this new dataset. @pdehaye ?

**Comment by Branko-Dj** [comment]
FIXED, The repo is located under `datasets` organization https://github.com/datasets/natural-gas-prices and it is also live on `datahub` https://datahub.io/core/natural-gas

**Comment by rufuspollock** [comment]
@Branko-Dj great this up. One comment: this dataset should be named `natural-gas-prices` not natural gas (as per repo name). Please can we get this corrected in the datapackage.json and on datahub.io
