### ISSUE TITLE
[meta] Improving Documentation (Feb 2015)

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#75]
This is a generic issue for collecting items re better documentation and workflow

Once we have clear issues and/or recommendations we should probably open an issue on https://github.com/okfn/data.okfn.org/issues and then fix. Relevant issues:

* [super] Publishing data tutorials / patterns - https://github.com/okfn/data.okfn.org/issues/91
* Publishing FAQ - https://github.com/okfn/data.okfn.org/issues/154

**Comment by rgrp** [comment]
@ekoner asked in #71 

1. I've named the file sic-2007-condensed.csv - does this meet naming conventions and where can I find these?
  * **We do not have these and we should add them to (new) http://data.okfn.org/doc/publish-faq**
2. Title - Again, is there a naming convention for this? I've gone with "UK condensed standard industrial classification of economic activities (SIC) 2007 codes"
  * **Ditto**
3. Name - Same as title? Abbreviated? I've used "UK Condensed SIC 2007"
  * See http://data.okfn.org/doc/publish-faq (which has guidance here)
4. License - Can't select or type in, so I'm assuming it goes somewhere else.
  * **This is now fixed in http://data.okfn.org/tools/create** /cc @sxren

**Comment by rgrp** [comment]
We need better instructions re license application and recording source license info - see e.g. #35 discussion

**Comment by pdehaye** [comment]
This looks like it has been fixed. For file naming and licensing issues, look at http://data.okfn.org/doc/publish-faq
