### ISSUE TITLE
Have the "date" data published/updated mentioned on the package page? 

### ISSUE THREAD

**Issue by bluechi** [datasets/registry#82]
I noticed that the data package does not mention the date/time of the most recent update to the data, I think this will be helpful so that those who want to use the data have an idea of how recent this data is.

**Comment by rgrp** [comment]
@bluechi we had it but it got removed https://github.com/dataprotocols/dataprotocols/issues/83 - the basic logic is that last modified is often not modified so it becomes stale. For git based data packages you can just look at commits (which it would be nice to show on data.okfn.org/data ...)

**Comment by bluechi** [comment]
@rgrp Thanks for the quick response! Yeah, showing something like"last commit" date could be helpful.

**Comment by rgrp** [comment]
@bluechi do you want to open an issue on https://github.com/okfn/data.okfn.org/issues suggesting something about showing the github commit history on the view page (for data packages sorted in github).

**Comment by bluechi** [comment]
@rgrp done. Here is the link. https://github.com/okfn/data.okfn.org/issues/175
