### ISSUE TITLE
GeoIP dataset

### ISSUE THREAD

**Issue by rgrp** [datasets/registry#84]
What databases are there? Is there an open one out there?

Probably take a look at http://datahub.io/

**Comment by edobejar** [comment]
Maxmind has downloadable databases in CSV format with CC BY-SA 3.0 license:
http://dev.maxmind.com/geoip/geoip2/geolite2/

**Comment by rgrp** [comment]
@edobejar perfect. How big is the file? Would it be worth looking at data packaging this?

**Comment by edobejar** [comment]
Did this first approach. There were two different CSV, one with fields like network, geoname_id and the other with geoname_id, country_name. Made a script to combine both and create a single CSV dataset (172755 rows in total - 11MB), with the following considerations:
- Where geoname_id was not available, registered_country_geoname_id was used.
- Where geoname_id and registered_country_genoname_id where empty, geoname_id, continent_code, continent_name, country_iso_code and country_name are empty.

https://github.com/edobejar/geoip2

**Comment by rgrp** [comment]
@edobejar great work and this should go in. A few minor suggestions:

* Can we tweak the README.md in line with suggestions at http://data.okfn.org/doc/publish-faq#sections
* Can we fix indentation / formatting in https://github.com/edobejar/geoip2/blob/master/datapackage.json
* Can you drop in the links to the validation and view in here as comments as per http://data.okfn.org/doc/core-data-curators#3-quality-assurance

@Yannael are you happy to help review here.

**Comment by Yannael** [comment]
@rgrp yes
@edobejar 
Looks quite good
* The title might give too many details. I would suggest 'IPv4 geolocation', and leave information regarding data source and last update in the README file.
* There is a typo for the type of the field 'continent_name' ('tring' instead of 'string')

**Comment by edobejar** [comment]
Done, updated with your suggestions. Here are the links:

* Validation:<br>
http://data.okfn.org/tools/validate?url=https%3A%2F%2Fgithub.com%2Fedobejar%2Fgeoip2
* View: <br>
http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fedobejar%2Fgeoip2

Best!

Edo

**Comment by Yannael** [comment]
Great!
Regarding the README conventions at http://data.okfn.org/doc/publish-faq#sections, 
* could you add a section 'Preparation' explaining how you created the dataset (did you use a script, or manually arranged the two files) ?
* and start the README without header (i.e. remove 'IPv4 geolocation datapackage', since it is not displayed nicely in the datapackage viewer) 
Thanks!

**Comment by rgrp** [comment]
@edobejar how you doing there - this would be a great dataset to get in.

**Comment by rgrp** [comment]
@edobejar / @Yannael how's it going?

**Comment by edobejar** [comment]
Hi, just updated datapackage with Yannael's suggestions for readme.
https://github.com/edobejar/geoip2/

**Comment by Yannael** [comment]
Hi @edobejar 
Great! Can you transfer the ownership to me, so I can then transfer it to github/datasets? (this is in settings, transfer ownership) ?

**Comment by Yannael** [comment]
@edobejar 
A reminder for the transfer, so we can make it available on the portal. Thanks!

**Comment by Yannael** [comment]
Hi @edobejar 
A reminder for the transfer!

**Comment by edobejar** [comment]
Hi @Yannael, transfer done. How do I maintain it after transferring it?

**Comment by Yannael** [comment]
Hi @edobejar 
Nice, added to core packages
@rgrp 
For the maintenance, what is the best way?

**Comment by rgrp** [comment]
Sorry for slow response.

@Yannael we should keep @edobejar an admin on the repo after the transfer (just create a dedicated team if necessary).

Great work all and look forward to having this closed and a tweet announcing the new core dataset!

**Comment by Yannael** [comment]
@edobejar @rgrp 
Ok, added a team for the repo, and twitted about it!
