### ISSUE TITLE
Free/Open licenses  

### ISSUE THREAD

**Issue by Ebnalblad** [datasets/registry#85]
I am thinking about doing Free/Open licenses database, what do you think about that ? and if anybody is interested to work with me that would great.

**Comment by rgrp** [comment]
I think we want to data package-ise https://github.com/okfn/licenses - if you are interested can i suggest opening an issue on that repo and we'll discuss with other folks who have worked on this and move it forward.

**Comment by Ebnalblad** [comment]
Sure

**Comment by Yannael** [comment]
@rgrp Shall we add the link https://github.com/okfn/licenses to catalog-list so the datapackage is available from http://data.okfn.org ?

**Comment by rgrp** [comment]
@Yannael great suggestion and we can then close this.

**Comment by Yannael** [comment]
@rgrp Added to catalog list and reloaded http://data.okfn.org/data/
Shouldn't this one be added to core as well? In this case, does it need to be in the datasets repo (as all the other core datasets) ?

**Comment by rgrp** [comment]
FIXED. http://data.okfn.org/data/okfn/licenses

@Yannael i'm not sure this is core so happy to leave there it is.

Well done all!
