### ISSUE TITLE
Free/Open Licenses Data Package

### ISSUE THREAD

**Issue by Ebnalblad** [datasets/registry#86]
I have been following the issues about Core Datasets as Data Packages project (http://data.okfn.org/roadmap/core-datasets) and I suggested to make data package for Free/Open Licenses https://github.com/datasets/registry/issues/85
 @rgrp told me that you had already worked on Free/Open Licenses data, so what do you think about my suggestion ?

**Comment by rgrp** [comment]
DUPLICATE of #85

**Comment by Ebnalblad** [comment]
Sorry, I made a mistake I wrote here instead of writing on https://github.com/okfn/licenses/issues
